// Auto-generated by typesafe-i18n
// DO NOT MODIFY BY HAND
//
// L — locale dictionary object for direct key lookup.
// Usage:
//   import { L } from './i18n-util.js';
//   L['ai.timeout']  // → "AI 调用超时（秒），范围 1-600"
//
// NOTE: typesafe-i18n's codegen CLI is incompatible with bun's TypeScript
// runtime (ts.createProgram unavailable). These files are manually maintained
// to match the typesafe-i18n output format.

import type { Translation } from './i18n-types.js';
import zh from './zh/index.json' with { type: 'json' };

export type LocaleTranslations = Translation;

/**
 * Direct locale dictionary — maps key → Chinese string at module load time.
 * No runtime locale initialization needed.
 */
export const L: Translation = zh;

/** Available locales (currently only zh). */
export type Locale = 'zh';
export const locales: Locale[] = ['zh'];

/** Current locale (always zh for now). */
export const locale: Locale = 'zh';

/** Load a locale (no-op for now; future: dynamic import). */
export function loadLocale(_locale: Locale): void {
  // Future: enable locale switching
}
