// i18n runtime dictionary — L maps key → Chinese string at module load time.
//
// History: previously generated by typesafe-i18n's CLI; that generator needs
// the legacy TS compiler JS API (`ts.createProgram`), removed in TypeScript 7.
// These are now hand-maintained modules with zero external dependencies.
//
// Usage:
//   import { L } from './i18n-util.js';
//   L['ai.timeout']  // → "AI 调用超时（秒），范围 1-600"
//
// SSOT: packages/shared/src/i18n/zh/index.json
// Drift gate: `bun scripts/check-i18n-keys.ts`（挂于 just qa）。

import type { Translation } from './i18n-types.js';
import zh from './zh/index.json' with { type: 'json' };

/**
 * Direct locale dictionary — maps key → Chinese string at module load time.
 * No runtime locale initialization needed.
 */
export const L: Translation = zh;

/** Available locales (currently only zh). */
export type Locale = 'zh';
export const locales: Locale[] = ['zh'];

/** Current locale (always zh for now). */
export const locale: Locale = 'zh';

/** Load a locale (no-op for now; future: dynamic import). */
export function loadLocale(_locale: Locale): void {
  // Future: enable locale switching
}
