#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
OUTPUT_DIR="$ROOT_DIR/sdk/client/python"
CONFIG_FILE="$ROOT_DIR/scripts/sdk/openapi-python-client.yaml"
SCHEMA_PATH="$ROOT_DIR/frontend/web/openapi.json"
BACKEND_PYPROJECT="$ROOT_DIR/backend/py/pyproject.toml"

if [[ ! -f "$BACKEND_PYPROJECT" ]]; then
  echo "backend/py/pyproject.toml not found at $BACKEND_PYPROJECT" >&2
  exit 1
fi

BACKEND_VERSION=$(BACKEND_PYPROJECT="$BACKEND_PYPROJECT" python - << 'PY'
import os
import tomllib
from pathlib import Path

path = Path(os.environ["BACKEND_PYPROJECT"])
data = tomllib.loads(path.read_text())
print(data["project"]["version"])
PY
)

if [[ -z "${SDK_VERSION:-}" ]]; then
  SDK_VERSION="$BACKEND_VERSION"
elif [[ "$SDK_VERSION" != "$BACKEND_VERSION" ]]; then
  echo "SDK_VERSION (${SDK_VERSION}) must match backend version (${BACKEND_VERSION})" >&2
  exit 1
fi

# Ensure OpenAPI schema exists (export if missing)
if [[ ! -f "$SCHEMA_PATH" ]]; then
  echo "OpenAPI schema not found at $SCHEMA_PATH" >&2
  echo "Run: cd backend/py && uv run scripts/api_schema.py export -o $SCHEMA_PATH" >&2
  exit 1
fi

TMP_CONFIG=$(mktemp)
trap 'rm -f "$TMP_CONFIG"' EXIT
cat "$CONFIG_FILE" > "$TMP_CONFIG"
echo "package_version_override: ${SDK_VERSION}" >> "$TMP_CONFIG"

# Generate SDK
openapi-python-client generate \
  --path "$SCHEMA_PATH" \
  --meta uv \
  --config "$TMP_CONFIG" \
  --output-path "$OUTPUT_DIR" \
  --overwrite

# Add LICENSE for distribution
cp "$ROOT_DIR/LICENSE" "$OUTPUT_DIR/LICENSE"

# Mark as generated
cat > "$OUTPUT_DIR/.generated" << 'MARKER'
# This directory is generated by scripts/sdk/generate_python_sdk.sh
# Do not edit manually.
MARKER

# Add generated marker README if missing
if [[ ! -f "$OUTPUT_DIR/README.generated.md" ]]; then
  cat > "$OUTPUT_DIR/README.generated.md" << 'MARKER'
# Generated Python SDK

This directory is auto-generated from the backend OpenAPI schema.

- Do not edit files here manually.
- Changes are produced by the release workflow on `v*` tags.
- The generated README.md comes from the generator.
MARKER
fi

# Add gitignore if missing
if [[ ! -f "$OUTPUT_DIR/.gitignore" ]]; then
  cat > "$OUTPUT_DIR/.gitignore" << 'GITIGNORE'
# Build artifacts
build/
dist/
*.egg-info/

# Local environments
.venv/
__pycache__/
GITIGNORE
fi
