#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
SDK_PATH="${SDK_PATH:-sdk/client/python}"
OUTPUT_DIR="$ROOT_DIR/$SDK_PATH"
SCHEMA_PATH="$ROOT_DIR/frontend/web/openapi.json"
BACKEND_PYPROJECT="$ROOT_DIR/backend/py/pyproject.toml"
FERN_DIR="$ROOT_DIR/fern"
GENERATORS_FILE="$FERN_DIR/generators.yml"
FERN_CONFIG="$FERN_DIR/fern.config.json"

if [[ ! -f "$BACKEND_PYPROJECT" ]]; then
  echo "backend/py/pyproject.toml not found at $BACKEND_PYPROJECT" >&2
  exit 1
fi

BACKEND_VERSION=$(BACKEND_PYPROJECT="$BACKEND_PYPROJECT" python - << 'PY'
import os
import re
from pathlib import Path

path = Path(os.environ["BACKEND_PYPROJECT"])
data = path.read_text()
match = re.search(r'^version\s*=\s*"([^"]+)"', data, re.MULTILINE)
if not match:
    raise SystemExit("version not found in backend/py/pyproject.toml")
print(match.group(1))
PY
)

if [[ -z "${SDK_VERSION:-}" ]]; then
  SDK_VERSION="$BACKEND_VERSION"
elif [[ "$SDK_VERSION" != "$BACKEND_VERSION" ]]; then
  echo "SDK_VERSION (${SDK_VERSION}) must match backend version (${BACKEND_VERSION})" >&2
  exit 1
fi

# Ensure Fern config exists
if [[ ! -f "$FERN_CONFIG" || ! -f "$GENERATORS_FILE" ]]; then
  echo "Fern config not found. Expected $FERN_CONFIG and $GENERATORS_FILE" >&2
  exit 1
fi

# Ensure fern CLI is available
if ! command -v fern >/dev/null 2>&1; then
  echo "fern CLI not found in PATH. Install it with: pnpm install -g fern-api" >&2
  exit 1
fi

# Ensure OpenAPI schema exists (export if missing)
if [[ ! -f "$SCHEMA_PATH" ]]; then
  echo "OpenAPI schema not found at $SCHEMA_PATH" >&2
  echo "Run: cd backend/py && uv run scripts/api_schema.py export -o $SCHEMA_PATH" >&2
  exit 1
fi

# Generate SDK
(
  cd "$ROOT_DIR"
  fern generate --local --force --group python-sdk --version "$SDK_VERSION"
)

# Verify Fern output and write version marker
METADATA_PATH="$OUTPUT_DIR/.fern/metadata.json"
if [[ ! -f "$METADATA_PATH" ]]; then
  echo "Fern metadata not found at $METADATA_PATH. Ensure generation succeeded." >&2
  exit 1
fi

PYPROJECT_PATH="$OUTPUT_DIR/pyproject.toml"
if [[ -f "$PYPROJECT_PATH" ]]; then
  GENERATED_VERSION=$(PYPROJECT_PATH="$PYPROJECT_PATH" python - << 'PY'
import os
import re
from pathlib import Path

path = Path(os.environ["PYPROJECT_PATH"])
data = path.read_text()
match = re.search(r'^version\s*=\s*"([^"]+)"', data, re.MULTILINE)
if not match:
    raise SystemExit("version not found in sdk/client/python/pyproject.toml")
print(match.group(1))
PY
  )
  if [[ "$GENERATED_VERSION" != "$SDK_VERSION" ]]; then
    echo "Generated SDK version (${GENERATED_VERSION}) must match backend version (${SDK_VERSION})" >&2
    exit 1
  fi
fi

SDK_VERSION_FILE="$OUTPUT_DIR/.sdk-version"
echo "$SDK_VERSION" > "$SDK_VERSION_FILE"

# Add LICENSE for distribution
cp "$ROOT_DIR/LICENSE" "$OUTPUT_DIR/LICENSE"

# Mark as generated
cat > "$OUTPUT_DIR/.generated" << 'MARKER'
# This directory is generated by scripts/sdk/generate_python_sdk.sh (Fern).
# Do not edit manually.
MARKER

# Add generated marker README if missing
if [[ ! -f "$OUTPUT_DIR/README.generated.md" ]]; then
  cat > "$OUTPUT_DIR/README.generated.md" << 'MARKER'
# Generated Python SDK

This directory is auto-generated from the backend OpenAPI schema via Fern.

- Do not edit files here manually.
- Changes are produced by manual SDK generation.
- The generated README.md comes from the generator.
MARKER
fi

# Add gitignore if missing
if [[ ! -f "$OUTPUT_DIR/.gitignore" ]]; then
  cat > "$OUTPUT_DIR/.gitignore" << 'GITIGNORE'
# Build artifacts
build/
dist/
*.egg-info/

# Local environments
.venv/
__pycache__/
GITIGNORE
fi
