# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.convert_session_to_output_response import ConvertSessionToOutputResponse
from ..types.convert_session_to_source_response import ConvertSessionToSourceResponse
from ..types.session_read import SessionRead
from .raw_client import AsyncRawSessionsClient, RawSessionsClient
from .types.convert_session_to_output_request_output_type import ConvertSessionToOutputRequestOutputType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SessionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSessionsClient
        """
        return self._raw_client

    def list_sessions(
        self,
        notebook_id: int,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[SessionRead]:
        """
        Parameters
        ----------
        notebook_id : int

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SessionRead]
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sessions.list_sessions(
            notebook_id=1,
        )
        """
        _response = self._raw_client.list_sessions(
            notebook_id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def create_session(
        self,
        notebook_id: int,
        *,
        title: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SessionRead:
        """
        Parameters
        ----------
        notebook_id : int

        title : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SessionRead
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sessions.create_session(
            notebook_id=1,
        )
        """
        _response = self._raw_client.create_session(notebook_id, title=title, request_options=request_options)
        return _response.data

    def get_session(
        self, notebook_id: int, session_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SessionRead:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SessionRead
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sessions.get_session(
            notebook_id=1,
            session_id=1,
        )
        """
        _response = self._raw_client.get_session(notebook_id, session_id, request_options=request_options)
        return _response.data

    def delete_session(
        self, notebook_id: int, session_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sessions.delete_session(
            notebook_id=1,
            session_id=1,
        )
        """
        _response = self._raw_client.delete_session(notebook_id, session_id, request_options=request_options)
        return _response.data

    def update_session(
        self,
        notebook_id: int,
        session_id: int,
        *,
        title: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SessionRead:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        title : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SessionRead
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sessions.update_session(
            notebook_id=1,
            session_id=1,
        )
        """
        _response = self._raw_client.update_session(
            notebook_id, session_id, title=title, request_options=request_options
        )
        return _response.data

    def convert_session_to_output(
        self,
        notebook_id: int,
        session_id: int,
        *,
        message_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        output_type: typing.Optional[ConvertSessionToOutputRequestOutputType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConvertSessionToOutputResponse:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        message_ids : typing.Optional[typing.Sequence[int]]
            Specific message IDs to convert. If null, converts entire session.

        output_type : typing.Optional[ConvertSessionToOutputRequestOutputType]
            Type of output to create.

            * `FAQ`: 问答清单
            * `GUIDE`: 学习/行动指南
            * `TIMELINE`: 关键事件序列
            * `MINDMAP`: 主题层级结构
            * `QUIZ`: 知识检验
            * `BRIEFING`: 高层摘要
            * `SLIDES`: 演示文稿
            * `PARAGRAPH`: 段落摘要
            * `BULLETS`: 要点列表
            * `STRUCTURED`: 结构化摘要

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConvertSessionToOutputResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sessions.convert_session_to_output(
            notebook_id=1,
            session_id=1,
        )
        """
        _response = self._raw_client.convert_session_to_output(
            notebook_id, session_id, message_ids=message_ids, output_type=output_type, request_options=request_options
        )
        return _response.data

    def convert_session_to_source(
        self,
        notebook_id: int,
        session_id: int,
        *,
        message_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConvertSessionToSourceResponse:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        message_ids : typing.Optional[typing.Sequence[int]]
            Specific message IDs to convert. If null, converts entire session.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConvertSessionToSourceResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sessions.convert_session_to_source(
            notebook_id=1,
            session_id=1,
        )
        """
        _response = self._raw_client.convert_session_to_source(
            notebook_id, session_id, message_ids=message_ids, request_options=request_options
        )
        return _response.data


class AsyncSessionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSessionsClient
        """
        return self._raw_client

    async def list_sessions(
        self,
        notebook_id: int,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[SessionRead]:
        """
        Parameters
        ----------
        notebook_id : int

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SessionRead]
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sessions.list_sessions(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_sessions(
            notebook_id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def create_session(
        self,
        notebook_id: int,
        *,
        title: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SessionRead:
        """
        Parameters
        ----------
        notebook_id : int

        title : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SessionRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sessions.create_session(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_session(notebook_id, title=title, request_options=request_options)
        return _response.data

    async def get_session(
        self, notebook_id: int, session_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SessionRead:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SessionRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sessions.get_session(
                notebook_id=1,
                session_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_session(notebook_id, session_id, request_options=request_options)
        return _response.data

    async def delete_session(
        self, notebook_id: int, session_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sessions.delete_session(
                notebook_id=1,
                session_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_session(notebook_id, session_id, request_options=request_options)
        return _response.data

    async def update_session(
        self,
        notebook_id: int,
        session_id: int,
        *,
        title: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SessionRead:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        title : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SessionRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sessions.update_session(
                notebook_id=1,
                session_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_session(
            notebook_id, session_id, title=title, request_options=request_options
        )
        return _response.data

    async def convert_session_to_output(
        self,
        notebook_id: int,
        session_id: int,
        *,
        message_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        output_type: typing.Optional[ConvertSessionToOutputRequestOutputType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConvertSessionToOutputResponse:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        message_ids : typing.Optional[typing.Sequence[int]]
            Specific message IDs to convert. If null, converts entire session.

        output_type : typing.Optional[ConvertSessionToOutputRequestOutputType]
            Type of output to create.

            * `FAQ`: 问答清单
            * `GUIDE`: 学习/行动指南
            * `TIMELINE`: 关键事件序列
            * `MINDMAP`: 主题层级结构
            * `QUIZ`: 知识检验
            * `BRIEFING`: 高层摘要
            * `SLIDES`: 演示文稿
            * `PARAGRAPH`: 段落摘要
            * `BULLETS`: 要点列表
            * `STRUCTURED`: 结构化摘要

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConvertSessionToOutputResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sessions.convert_session_to_output(
                notebook_id=1,
                session_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.convert_session_to_output(
            notebook_id, session_id, message_ids=message_ids, output_type=output_type, request_options=request_options
        )
        return _response.data

    async def convert_session_to_source(
        self,
        notebook_id: int,
        session_id: int,
        *,
        message_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConvertSessionToSourceResponse:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        message_ids : typing.Optional[typing.Sequence[int]]
            Specific message IDs to convert. If null, converts entire session.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConvertSessionToSourceResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sessions.convert_session_to_source(
                notebook_id=1,
                session_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.convert_session_to_source(
            notebook_id, session_id, message_ids=message_ids, request_options=request_options
        )
        return _response.data
