"""initial

Revision ID: 963103e80f8e
Revises:
Create Date: 2026-02-08 12:45:42.423035

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '963103e80f8e'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.create_index('ix_notebooks_name', ['name'], unique=False)

    op.create_table('outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FAQ', 'GUIDE', 'TIMELINE', 'MINDMAP', 'QUIZ', 'BRIEFING', 'SLIDES', 'PARAGRAPH', 'BULLETS', 'STRUCTURED', name='output_type'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('chunk_ids', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outputs_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index('ix_outputs_notebook_id_created_at', ['notebook_id', 'created_at'], unique=False)

    op.create_table('research_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('planning', 'searching', 'analyzing', 'waiting_user', 'completed', 'cancelled', name='research_status'), server_default=sa.text("'planning'"), nullable=False),
    sa.Column('current_iteration', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_iterations', sa.Integer(), server_default=sa.text('4'), nullable=False),
    sa.Column('aggregated_results', sa.JSON(), nullable=True),
    sa.Column('final_report', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sessions_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index('ix_research_sessions_status', ['status'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index('ix_sessions_notebook_id_updated_at', ['notebook_id', 'updated_at'], unique=False)

    op.create_table('source_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notebook_id', 'name', name='uq_source_tags_notebook_id_name')
    )
    with op.batch_alter_table('source_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_tags_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index('ix_source_tags_notebook_id_name', ['notebook_id', 'name'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=True),
    sa.Column('parser_type', sa.String(length=64), server_default=sa.text("'text'"), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'ready', 'failed', name='source_status'), server_default=sa.text("'processing'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index('ix_sources_notebook_id_status', ['notebook_id', 'status'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('refine', 'document_parse', name='task_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='task_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index('ix_tasks_notebook_id_status', ['notebook_id', 'status'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'chunk_index', name='uq_chunks_source_id_chunk_index')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_chunks_source_id_chunk_index', ['source_id', 'chunk_index'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_messages_session_id_created_at', ['session_id', 'created_at'], unique=False)

    op.create_table('research_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('plan', 'search', 'analyze', 'user_input', 'summary', name='research_step_type'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'skipped', name='research_step_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_steps_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_research_steps_session_iteration', ['session_id', 'iteration'], unique=False)

    op.create_table('source_tag_map',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['source_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'tag_id')
    )
    with op.batch_alter_table('source_tag_map', schema=None) as batch_op:
        batch_op.create_index('ix_source_tag_map_tag_id', ['tag_id'], unique=False)

    op.create_table('studio_slides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('output_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('engine', sa.String(length=64), server_default=sa.text("'slidev'"), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=True),
    sa.Column('source_ids', sa.JSON(), nullable=True),
    sa.Column('outline', sa.JSON(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('generation_config', sa.JSON(), nullable=True),
    sa.Column('stage', sa.Enum('input', 'outline', 'markdown', name='slide_stage'), server_default=sa.text("'input'"), nullable=False),
    sa.Column('status', sa.Enum('idle', 'running', 'error', name='slide_status'), server_default=sa.text("'idle'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['output_id'], ['outputs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studio_slides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studio_slides_notebook_id'), ['notebook_id'], unique=False)
        batch_op.create_index('ix_studio_slides_notebook_id_updated_at', ['notebook_id', 'updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studio_slides', schema=None) as batch_op:
        batch_op.drop_index('ix_studio_slides_notebook_id_updated_at')
        batch_op.drop_index(batch_op.f('ix_studio_slides_notebook_id'))

    op.drop_table('studio_slides')
    with op.batch_alter_table('source_tag_map', schema=None) as batch_op:
        batch_op.drop_index('ix_source_tag_map_tag_id')

    op.drop_table('source_tag_map')
    with op.batch_alter_table('research_steps', schema=None) as batch_op:
        batch_op.drop_index('ix_research_steps_session_iteration')
        batch_op.drop_index(batch_op.f('ix_research_steps_session_id'))

    op.drop_table('research_steps')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_session_id_created_at')
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))

    op.drop_table('messages')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_chunks_source_id_chunk_index')
        batch_op.drop_index(batch_op.f('ix_chunks_source_id'))

    op.drop_table('chunks')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_notebook_id_status')
        batch_op.drop_index(batch_op.f('ix_tasks_notebook_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('ix_sources_notebook_id_status')
        batch_op.drop_index(batch_op.f('ix_sources_notebook_id'))

    op.drop_table('sources')
    with op.batch_alter_table('source_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_source_tags_notebook_id_name')
        batch_op.drop_index(batch_op.f('ix_source_tags_notebook_id'))

    op.drop_table('source_tags')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_notebook_id_updated_at')
        batch_op.drop_index(batch_op.f('ix_sessions_notebook_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_research_sessions_status')
        batch_op.drop_index(batch_op.f('ix_research_sessions_notebook_id'))

    op.drop_table('research_sessions')
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.drop_index('ix_outputs_notebook_id_created_at')
        batch_op.drop_index(batch_op.f('ix_outputs_notebook_id'))

    op.drop_table('outputs')
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.drop_index('ix_notebooks_name')

    op.drop_table('notebooks')
    # ### end Alembic commands ###
