# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Citation(UniversalBaseModel):
    chunk_id: int
    chunk_index: int
    page_number: typing.Optional[int] = None
    paragraph_index: typing.Optional[int] = None
    score: typing.Optional[float] = None
    snippet: str
    source_id: int
    source_name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
