# This file was auto-generated by Fern from our API Definition.

import typing

FieldDescriptorType = typing.Union[
    typing.Literal["badge", "citation", "code", "date", "heading", "list", "text", "tree"], typing.Any
]
