# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .research_step_response_status import ResearchStepResponseStatus
from .research_step_response_type import ResearchStepResponseType


class ResearchStepResponse(UniversalBaseModel):
    """
    Response model for a research step.
    """

    created_at: dt.datetime
    id: int
    input_data: typing.Optional[typing.Dict[str, typing.Any]] = None
    iteration: int
    output_data: typing.Optional[typing.Dict[str, typing.Any]] = None
    session_id: int
    status: ResearchStepResponseStatus = pydantic.Field()
    """
    枚举值:

    * `pending`: 等待执行
    * `running`: 正在执行
    * `completed`: 执行完成
    * `skipped`: 已跳过
    """

    type: ResearchStepResponseType = pydantic.Field()
    """
    枚举值:

    * `plan`: 搜索计划
    * `search`: 执行搜索
    * `analyze`: 分析结果
    * `user_input`: 用户输入
    * `summary`: 生成报告
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
