# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .slide_generation_config import SlideGenerationConfig
from .slides_config_option import SlidesConfigOption
from .slides_theme_preset import SlidesThemePreset


class SlidesConfigResponse(UniversalBaseModel):
    audience_options: typing.List[SlidesConfigOption]
    defaults: SlideGenerationConfig
    density_options: typing.List[SlidesConfigOption]
    language_options: typing.List[SlidesConfigOption]
    quantity_options: typing.List[SlidesConfigOption]
    structure_options: typing.List[SlidesConfigOption]
    theme_preset_options: typing.List[SlidesThemePreset]
    tone_options: typing.List[SlidesConfigOption]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
