# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .plugin_config_schema import PluginConfigSchema
from .render_descriptor import RenderDescriptor
from .workspace_tool_output_type import WorkspaceToolOutputType
from .workspace_tool_tone import WorkspaceToolTone


class WorkspaceTool(UniversalBaseModel):
    badge: typing.Optional[str] = None
    config_schema: typing.Optional[PluginConfigSchema] = None
    description: str
    enabled: typing.Optional[bool] = None
    id: str
    label: str
    output_type: WorkspaceToolOutputType = pydantic.Field()
    """
    枚举值:

    * `FAQ`: 问答清单
    * `GUIDE`: 学习/行动指南
    * `TIMELINE`: 关键事件序列
    * `MINDMAP`: 主题层级结构
    * `QUIZ`: 知识检验
    * `BRIEFING`: 高层摘要
    * `SLIDES`: 演示文稿
    * `PARAGRAPH`: 段落摘要
    * `BULLETS`: 要点列表
    * `STRUCTURED`: 结构化摘要
    """

    prompt: str
    render_descriptor: typing.Optional[RenderDescriptor] = None
    tone: WorkspaceToolTone

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(WorkspaceTool)
