# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.slides_config_response import SlidesConfigResponse
from ..types.tool_config_response import ToolConfigResponse
from ..types.workspace_tools_response import WorkspaceToolsResponse
from .raw_client import AsyncRawWorkspaceToolsClient, RawWorkspaceToolsClient


class WorkspaceToolsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWorkspaceToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWorkspaceToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWorkspaceToolsClient
        """
        return self._raw_client

    def list_workspace_tools(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkspaceToolsResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkspaceToolsResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.workspace_tools.list_workspace_tools()
        """
        _response = self._raw_client.list_workspace_tools(request_options=request_options)
        return _response.data

    def get_slides_config(self, *, request_options: typing.Optional[RequestOptions] = None) -> SlidesConfigResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlidesConfigResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.workspace_tools.get_slides_config()
        """
        _response = self._raw_client.get_slides_config(request_options=request_options)
        return _response.data

    def get_tool_config(
        self, tool_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ToolConfigResponse:
        """
        Get configuration options for a specific tool.

        Parameters
        ----------
        tool_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolConfigResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.workspace_tools.get_tool_config(
            tool_id="tool_id",
        )
        """
        _response = self._raw_client.get_tool_config(tool_id, request_options=request_options)
        return _response.data


class AsyncWorkspaceToolsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWorkspaceToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWorkspaceToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWorkspaceToolsClient
        """
        return self._raw_client

    async def list_workspace_tools(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WorkspaceToolsResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkspaceToolsResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.workspace_tools.list_workspace_tools()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_workspace_tools(request_options=request_options)
        return _response.data

    async def get_slides_config(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SlidesConfigResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlidesConfigResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.workspace_tools.get_slides_config()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_slides_config(request_options=request_options)
        return _response.data

    async def get_tool_config(
        self, tool_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ToolConfigResponse:
        """
        Get configuration options for a specific tool.

        Parameters
        ----------
        tool_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolConfigResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.workspace_tools.get_tool_config(
                tool_id="tool_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_tool_config(tool_id, request_options=request_options)
        return _response.data
