# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/refs/heads/main/generators-yml.schema.json

api:
  specs:
    - openapi: ../../../frontend/web/openapi.json

groups:
  python-sdk:
    generators:
      - name: fernapi/fern-python-sdk
        version: 4.53.1
        output:
          location: local-file-system
          path: ../../client/python
        config:
          package_name: crystalith
          client_class_name: CrystalithClient
