# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chunk_read import ChunkRead
from ..types.convert_source_qa_to_source_response import ConvertSourceQaToSourceResponse
from ..types.extractors_list_response import ExtractorsListResponse
from ..types.qa_message import QaMessage
from ..types.source_batch_delete_response import SourceBatchDeleteResponse
from ..types.source_batch_reembed_response import SourceBatchReembedResponse
from ..types.source_qa_response import SourceQaResponse
from ..types.source_read import SourceRead
from ..types.source_search_response import SourceSearchResponse
from ..types.source_summary_response import SourceSummaryResponse
from ..types.source_tag_read import SourceTagRead
from ..types.source_tag_source_binding_response import SourceTagSourceBindingResponse
from .raw_client import AsyncRawSourcesClient, RawSourcesClient
from .types.list_sources_v1notebooks_notebook_id_sources_get_request_sort_by import (
    ListSourcesV1NotebooksNotebookIdSourcesGetRequestSortBy,
)
from .types.list_sources_v1notebooks_notebook_id_sources_get_request_sort_order import (
    ListSourcesV1NotebooksNotebookIdSourcesGetRequestSortOrder,
)
from .types.source_from_url_request_mode import SourceFromUrlRequestMode

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SourcesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSourcesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSourcesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSourcesClient
        """
        return self._raw_client

    def list_sources(
        self,
        notebook_id: int,
        *,
        sort_by: typing.Optional[ListSourcesV1NotebooksNotebookIdSourcesGetRequestSortBy] = None,
        sort_order: typing.Optional[ListSourcesV1NotebooksNotebookIdSourcesGetRequestSortOrder] = None,
        tag: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[SourceRead]:
        """
        Parameters
        ----------
        notebook_id : int

        sort_by : typing.Optional[ListSourcesV1NotebooksNotebookIdSourcesGetRequestSortBy]

        sort_order : typing.Optional[ListSourcesV1NotebooksNotebookIdSourcesGetRequestSortOrder]

        tag : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SourceRead]
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.list_sources(
            notebook_id=1,
        )
        """
        _response = self._raw_client.list_sources(
            notebook_id, sort_by=sort_by, sort_order=sort_order, tag=tag, request_options=request_options
        )
        return _response.data

    def upload_source(
        self, notebook_id: int, *, file: core.File, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceRead:
        """
        Parameters
        ----------
        notebook_id : int

        file : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceRead
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.upload_source(
            notebook_id=1,
        )
        """
        _response = self._raw_client.upload_source(notebook_id, file=file, request_options=request_options)
        return _response.data

    def batch_delete_sources(
        self,
        notebook_id: int,
        *,
        source_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceBatchDeleteResponse:
        """
        Parameters
        ----------
        notebook_id : int

        source_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceBatchDeleteResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.batch_delete_sources(
            notebook_id=1,
            source_ids=[1],
        )
        """
        _response = self._raw_client.batch_delete_sources(
            notebook_id, source_ids=source_ids, request_options=request_options
        )
        return _response.data

    def batch_reembed_sources(
        self,
        notebook_id: int,
        *,
        source_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceBatchReembedResponse:
        """
        Parameters
        ----------
        notebook_id : int

        source_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceBatchReembedResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.batch_reembed_sources(
            notebook_id=1,
            source_ids=[1],
        )
        """
        _response = self._raw_client.batch_reembed_sources(
            notebook_id, source_ids=source_ids, request_options=request_options
        )
        return _response.data

    def list_extractors(
        self, notebook_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ExtractorsListResponse:
        """
        List available web content extractors.

        Returns information about all configured extractors, including:
        - Whether they are enabled in configuration
        - Whether they are actually available (dependencies installed, service reachable)
        - Display name and description
        - Priority order for fallback

        The frontend can use this to show users which extraction methods are available
        and let them choose a preferred method.

        Parameters
        ----------
        notebook_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExtractorsListResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.list_extractors(
            notebook_id=1,
        )
        """
        _response = self._raw_client.list_extractors(notebook_id, request_options=request_options)
        return _response.data

    def create_source_from_url(
        self,
        notebook_id: int,
        *,
        url: str,
        extractor: typing.Optional[str] = OMIT,
        mode: typing.Optional[SourceFromUrlRequestMode] = OMIT,
        snippet: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceRead:
        """
        Create a source from a URL.

        Supports two modes:
        - `link`: Save URL, title, and snippet as a lightweight source
        - `fetch`: Fetch the webpage content and parse it as a full source

        For `fetch` mode, you can optionally specify an extractor:
        - `trafilatura`: Local extraction using trafilatura library (default)
        - `firecrawl`: External API using Firecrawl service
        - `browserless`: Browser rendering using Browserless + Playwright

        Parameters
        ----------
        notebook_id : int

        url : str

        extractor : typing.Optional[str]
            指定使用的提取器类型 (trafilatura, firecrawl, browserless)。如果不指定，使用默认降级顺序。

        mode : typing.Optional[SourceFromUrlRequestMode]
            枚举值:

            * `fetch`: 获取完整内容
            * `link`: 仅保存链接

        snippet : typing.Optional[str]

        title : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceRead
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.create_source_from_url(
            notebook_id=1,
            url="url",
        )
        """
        _response = self._raw_client.create_source_from_url(
            notebook_id,
            url=url,
            extractor=extractor,
            mode=mode,
            snippet=snippet,
            title=title,
            request_options=request_options,
        )
        return _response.data

    def search_sources(
        self,
        notebook_id: int,
        *,
        query: str,
        engine: typing.Optional[str] = OMIT,
        mode: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceSearchResponse:
        """
        Parameters
        ----------
        notebook_id : int

        query : str

        engine : typing.Optional[str]

        mode : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceSearchResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.search_sources(
            notebook_id=1,
            query="query",
        )
        """
        _response = self._raw_client.search_sources(
            notebook_id, query=query, engine=engine, mode=mode, request_options=request_options
        )
        return _response.data

    def list_source_tags(
        self, notebook_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SourceTagRead]:
        """
        Parameters
        ----------
        notebook_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SourceTagRead]
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.list_source_tags(
            notebook_id=1,
        )
        """
        _response = self._raw_client.list_source_tags(notebook_id, request_options=request_options)
        return _response.data

    def create_source_tag(
        self, notebook_id: int, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceTagRead:
        """
        Parameters
        ----------
        notebook_id : int

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceTagRead
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.create_source_tag(
            notebook_id=1,
            name="name",
        )
        """
        _response = self._raw_client.create_source_tag(notebook_id, name=name, request_options=request_options)
        return _response.data

    def delete_source_tag(
        self, notebook_id: int, tag_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        notebook_id : int

        tag_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.delete_source_tag(
            notebook_id=1,
            tag_id=1,
        )
        """
        _response = self._raw_client.delete_source_tag(notebook_id, tag_id, request_options=request_options)
        return _response.data

    def update_source_tag(
        self, notebook_id: int, tag_id: int, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceTagRead:
        """
        Parameters
        ----------
        notebook_id : int

        tag_id : int

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceTagRead
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.update_source_tag(
            notebook_id=1,
            tag_id=1,
            name="name",
        )
        """
        _response = self._raw_client.update_source_tag(notebook_id, tag_id, name=name, request_options=request_options)
        return _response.data

    def assign_tag_to_sources(
        self,
        notebook_id: int,
        tag_id: int,
        *,
        source_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceTagSourceBindingResponse:
        """
        Parameters
        ----------
        notebook_id : int

        tag_id : int

        source_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceTagSourceBindingResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.assign_tag_to_sources(
            notebook_id=1,
            tag_id=1,
            source_ids=[1],
        )
        """
        _response = self._raw_client.assign_tag_to_sources(
            notebook_id, tag_id, source_ids=source_ids, request_options=request_options
        )
        return _response.data

    def remove_tag_from_sources(
        self,
        notebook_id: int,
        tag_id: int,
        *,
        source_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceTagSourceBindingResponse:
        """
        Parameters
        ----------
        notebook_id : int

        tag_id : int

        source_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceTagSourceBindingResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.remove_tag_from_sources(
            notebook_id=1,
            tag_id=1,
            source_ids=[1],
        )
        """
        _response = self._raw_client.remove_tag_from_sources(
            notebook_id, tag_id, source_ids=source_ids, request_options=request_options
        )
        return _response.data

    def delete_source(
        self, notebook_id: int, source_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        notebook_id : int

        source_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.delete_source(
            notebook_id=1,
            source_id=1,
        )
        """
        _response = self._raw_client.delete_source(notebook_id, source_id, request_options=request_options)
        return _response.data

    def list_source_chunks(
        self, notebook_id: int, source_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ChunkRead]:
        """
        获取来源的所有文本片段（chunks）。

        返回指定来源的所有文本片段，按 chunk_index 升序排列。
        每个片段包含：
        - id: 片段唯一标识
        - chunk_index: 片段索引（从0开始）
        - text: 片段文本内容
        - start_offset: 在原文中的起始位置
        - end_offset: 在原文中的结束位置
        - metadata: 片段元数据（如页码等）

        Parameters
        ----------
        notebook_id : int

        source_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ChunkRead]
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.list_source_chunks(
            notebook_id=1,
            source_id=1,
        )
        """
        _response = self._raw_client.list_source_chunks(notebook_id, source_id, request_options=request_options)
        return _response.data

    def source_qa(
        self,
        notebook_id: int,
        source_id: int,
        *,
        question: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceQaResponse:
        """
        Answer a question based on a specific source's content.

        Parameters
        ----------
        notebook_id : int

        source_id : int

        question : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceQaResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.source_qa(
            notebook_id=1,
            source_id=1,
            question="question",
        )
        """
        _response = self._raw_client.source_qa(
            notebook_id, source_id, question=question, request_options=request_options
        )
        return _response.data

    def convert_source_qa_to_source(
        self,
        notebook_id: int,
        source_id: int,
        *,
        messages: typing.Sequence[QaMessage],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConvertSourceQaToSourceResponse:
        """
        Convert source QA conversation to a new source document for RAG queries.

        Parameters
        ----------
        notebook_id : int

        source_id : int

        messages : typing.Sequence[QaMessage]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConvertSourceQaToSourceResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient, QaMessage

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.convert_source_qa_to_source(
            notebook_id=1,
            source_id=1,
            messages=[
                QaMessage(
                    content="content",
                    role="assistant",
                )
            ],
        )
        """
        _response = self._raw_client.convert_source_qa_to_source(
            notebook_id, source_id, messages=messages, request_options=request_options
        )
        return _response.data

    def reembed_source(
        self, notebook_id: int, source_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceRead:
        """
        Retry embedding for a failed source using existing chunks.

        Parameters
        ----------
        notebook_id : int

        source_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceRead
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.reembed_source(
            notebook_id=1,
            source_id=1,
        )
        """
        _response = self._raw_client.reembed_source(notebook_id, source_id, request_options=request_options)
        return _response.data

    def get_source_summary(
        self, notebook_id: int, source_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceSummaryResponse:
        """
        Generate or retrieve summary for a specific source.

        Parameters
        ----------
        notebook_id : int

        source_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceSummaryResponse
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.sources.get_source_summary(
            notebook_id=1,
            source_id=1,
        )
        """
        _response = self._raw_client.get_source_summary(notebook_id, source_id, request_options=request_options)
        return _response.data


class AsyncSourcesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSourcesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSourcesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSourcesClient
        """
        return self._raw_client

    async def list_sources(
        self,
        notebook_id: int,
        *,
        sort_by: typing.Optional[ListSourcesV1NotebooksNotebookIdSourcesGetRequestSortBy] = None,
        sort_order: typing.Optional[ListSourcesV1NotebooksNotebookIdSourcesGetRequestSortOrder] = None,
        tag: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[SourceRead]:
        """
        Parameters
        ----------
        notebook_id : int

        sort_by : typing.Optional[ListSourcesV1NotebooksNotebookIdSourcesGetRequestSortBy]

        sort_order : typing.Optional[ListSourcesV1NotebooksNotebookIdSourcesGetRequestSortOrder]

        tag : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SourceRead]
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.list_sources(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_sources(
            notebook_id, sort_by=sort_by, sort_order=sort_order, tag=tag, request_options=request_options
        )
        return _response.data

    async def upload_source(
        self, notebook_id: int, *, file: core.File, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceRead:
        """
        Parameters
        ----------
        notebook_id : int

        file : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.upload_source(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_source(notebook_id, file=file, request_options=request_options)
        return _response.data

    async def batch_delete_sources(
        self,
        notebook_id: int,
        *,
        source_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceBatchDeleteResponse:
        """
        Parameters
        ----------
        notebook_id : int

        source_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceBatchDeleteResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.batch_delete_sources(
                notebook_id=1,
                source_ids=[1],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.batch_delete_sources(
            notebook_id, source_ids=source_ids, request_options=request_options
        )
        return _response.data

    async def batch_reembed_sources(
        self,
        notebook_id: int,
        *,
        source_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceBatchReembedResponse:
        """
        Parameters
        ----------
        notebook_id : int

        source_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceBatchReembedResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.batch_reembed_sources(
                notebook_id=1,
                source_ids=[1],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.batch_reembed_sources(
            notebook_id, source_ids=source_ids, request_options=request_options
        )
        return _response.data

    async def list_extractors(
        self, notebook_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ExtractorsListResponse:
        """
        List available web content extractors.

        Returns information about all configured extractors, including:
        - Whether they are enabled in configuration
        - Whether they are actually available (dependencies installed, service reachable)
        - Display name and description
        - Priority order for fallback

        The frontend can use this to show users which extraction methods are available
        and let them choose a preferred method.

        Parameters
        ----------
        notebook_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExtractorsListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.list_extractors(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_extractors(notebook_id, request_options=request_options)
        return _response.data

    async def create_source_from_url(
        self,
        notebook_id: int,
        *,
        url: str,
        extractor: typing.Optional[str] = OMIT,
        mode: typing.Optional[SourceFromUrlRequestMode] = OMIT,
        snippet: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceRead:
        """
        Create a source from a URL.

        Supports two modes:
        - `link`: Save URL, title, and snippet as a lightweight source
        - `fetch`: Fetch the webpage content and parse it as a full source

        For `fetch` mode, you can optionally specify an extractor:
        - `trafilatura`: Local extraction using trafilatura library (default)
        - `firecrawl`: External API using Firecrawl service
        - `browserless`: Browser rendering using Browserless + Playwright

        Parameters
        ----------
        notebook_id : int

        url : str

        extractor : typing.Optional[str]
            指定使用的提取器类型 (trafilatura, firecrawl, browserless)。如果不指定，使用默认降级顺序。

        mode : typing.Optional[SourceFromUrlRequestMode]
            枚举值:

            * `fetch`: 获取完整内容
            * `link`: 仅保存链接

        snippet : typing.Optional[str]

        title : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.create_source_from_url(
                notebook_id=1,
                url="url",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_source_from_url(
            notebook_id,
            url=url,
            extractor=extractor,
            mode=mode,
            snippet=snippet,
            title=title,
            request_options=request_options,
        )
        return _response.data

    async def search_sources(
        self,
        notebook_id: int,
        *,
        query: str,
        engine: typing.Optional[str] = OMIT,
        mode: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceSearchResponse:
        """
        Parameters
        ----------
        notebook_id : int

        query : str

        engine : typing.Optional[str]

        mode : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceSearchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.search_sources(
                notebook_id=1,
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_sources(
            notebook_id, query=query, engine=engine, mode=mode, request_options=request_options
        )
        return _response.data

    async def list_source_tags(
        self, notebook_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SourceTagRead]:
        """
        Parameters
        ----------
        notebook_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SourceTagRead]
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.list_source_tags(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_source_tags(notebook_id, request_options=request_options)
        return _response.data

    async def create_source_tag(
        self, notebook_id: int, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceTagRead:
        """
        Parameters
        ----------
        notebook_id : int

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceTagRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.create_source_tag(
                notebook_id=1,
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_source_tag(notebook_id, name=name, request_options=request_options)
        return _response.data

    async def delete_source_tag(
        self, notebook_id: int, tag_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        notebook_id : int

        tag_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.delete_source_tag(
                notebook_id=1,
                tag_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_source_tag(notebook_id, tag_id, request_options=request_options)
        return _response.data

    async def update_source_tag(
        self, notebook_id: int, tag_id: int, *, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceTagRead:
        """
        Parameters
        ----------
        notebook_id : int

        tag_id : int

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceTagRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.update_source_tag(
                notebook_id=1,
                tag_id=1,
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_source_tag(
            notebook_id, tag_id, name=name, request_options=request_options
        )
        return _response.data

    async def assign_tag_to_sources(
        self,
        notebook_id: int,
        tag_id: int,
        *,
        source_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceTagSourceBindingResponse:
        """
        Parameters
        ----------
        notebook_id : int

        tag_id : int

        source_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceTagSourceBindingResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.assign_tag_to_sources(
                notebook_id=1,
                tag_id=1,
                source_ids=[1],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.assign_tag_to_sources(
            notebook_id, tag_id, source_ids=source_ids, request_options=request_options
        )
        return _response.data

    async def remove_tag_from_sources(
        self,
        notebook_id: int,
        tag_id: int,
        *,
        source_ids: typing.Sequence[int],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceTagSourceBindingResponse:
        """
        Parameters
        ----------
        notebook_id : int

        tag_id : int

        source_ids : typing.Sequence[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceTagSourceBindingResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.remove_tag_from_sources(
                notebook_id=1,
                tag_id=1,
                source_ids=[1],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_tag_from_sources(
            notebook_id, tag_id, source_ids=source_ids, request_options=request_options
        )
        return _response.data

    async def delete_source(
        self, notebook_id: int, source_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        notebook_id : int

        source_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.delete_source(
                notebook_id=1,
                source_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_source(notebook_id, source_id, request_options=request_options)
        return _response.data

    async def list_source_chunks(
        self, notebook_id: int, source_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ChunkRead]:
        """
        获取来源的所有文本片段（chunks）。

        返回指定来源的所有文本片段，按 chunk_index 升序排列。
        每个片段包含：
        - id: 片段唯一标识
        - chunk_index: 片段索引（从0开始）
        - text: 片段文本内容
        - start_offset: 在原文中的起始位置
        - end_offset: 在原文中的结束位置
        - metadata: 片段元数据（如页码等）

        Parameters
        ----------
        notebook_id : int

        source_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ChunkRead]
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.list_source_chunks(
                notebook_id=1,
                source_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_source_chunks(notebook_id, source_id, request_options=request_options)
        return _response.data

    async def source_qa(
        self,
        notebook_id: int,
        source_id: int,
        *,
        question: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SourceQaResponse:
        """
        Answer a question based on a specific source's content.

        Parameters
        ----------
        notebook_id : int

        source_id : int

        question : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceQaResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.source_qa(
                notebook_id=1,
                source_id=1,
                question="question",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.source_qa(
            notebook_id, source_id, question=question, request_options=request_options
        )
        return _response.data

    async def convert_source_qa_to_source(
        self,
        notebook_id: int,
        source_id: int,
        *,
        messages: typing.Sequence[QaMessage],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConvertSourceQaToSourceResponse:
        """
        Convert source QA conversation to a new source document for RAG queries.

        Parameters
        ----------
        notebook_id : int

        source_id : int

        messages : typing.Sequence[QaMessage]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConvertSourceQaToSourceResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient, QaMessage

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.convert_source_qa_to_source(
                notebook_id=1,
                source_id=1,
                messages=[
                    QaMessage(
                        content="content",
                        role="assistant",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.convert_source_qa_to_source(
            notebook_id, source_id, messages=messages, request_options=request_options
        )
        return _response.data

    async def reembed_source(
        self, notebook_id: int, source_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceRead:
        """
        Retry embedding for a failed source using existing chunks.

        Parameters
        ----------
        notebook_id : int

        source_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.reembed_source(
                notebook_id=1,
                source_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.reembed_source(notebook_id, source_id, request_options=request_options)
        return _response.data

    async def get_source_summary(
        self, notebook_id: int, source_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceSummaryResponse:
        """
        Generate or retrieve summary for a specific source.

        Parameters
        ----------
        notebook_id : int

        source_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceSummaryResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.sources.get_source_summary(
                notebook_id=1,
                source_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_source_summary(notebook_id, source_id, request_options=request_options)
        return _response.data
