# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.template_config_input import TemplateConfigInput
from ..types.template_read import TemplateRead
from .raw_client import AsyncRawTemplatesClient, RawTemplatesClient
from .types.template_from_notebook_create_output_type import TemplateFromNotebookCreateOutputType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TemplatesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTemplatesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTemplatesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTemplatesClient
        """
        return self._raw_client

    def save_notebook_as_template(
        self,
        notebook_id: int,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        output_type: typing.Optional[TemplateFromNotebookCreateOutputType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TemplateRead:
        """
        Parameters
        ----------
        notebook_id : int

        name : str

        description : typing.Optional[str]

        output_type : typing.Optional[TemplateFromNotebookCreateOutputType]
            Preferred default output type for the template.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TemplateRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.templates.save_notebook_as_template(
            notebook_id=1,
            name="name",
        )
        """
        _response = self._raw_client.save_notebook_as_template(
            notebook_id, name=name, description=description, output_type=output_type, request_options=request_options
        )
        return _response.data

    def list_templates(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[TemplateRead]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TemplateRead]
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.templates.list_templates()
        """
        _response = self._raw_client.list_templates(request_options=request_options)
        return _response.data

    def create_template(
        self,
        *,
        config_json: TemplateConfigInput,
        name: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TemplateRead:
        """
        Parameters
        ----------
        config_json : TemplateConfigInput

        name : str

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TemplateRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient, TemplateConfigInput

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.templates.create_template(
            config_json=TemplateConfigInput(),
            name="name",
        )
        """
        _response = self._raw_client.create_template(
            config_json=config_json, name=name, description=description, request_options=request_options
        )
        return _response.data

    def get_template(
        self, template_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TemplateRead:
        """
        Parameters
        ----------
        template_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TemplateRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.templates.get_template(
            template_id=1,
        )
        """
        _response = self._raw_client.get_template(template_id, request_options=request_options)
        return _response.data

    def delete_template(self, template_id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        template_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.templates.delete_template(
            template_id=1,
        )
        """
        _response = self._raw_client.delete_template(template_id, request_options=request_options)
        return _response.data

    def update_template(
        self,
        template_id: int,
        *,
        config_json: typing.Optional[TemplateConfigInput] = OMIT,
        description: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TemplateRead:
        """
        Parameters
        ----------
        template_id : int

        config_json : typing.Optional[TemplateConfigInput]

        description : typing.Optional[str]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TemplateRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.templates.update_template(
            template_id=1,
        )
        """
        _response = self._raw_client.update_template(
            template_id, config_json=config_json, description=description, name=name, request_options=request_options
        )
        return _response.data


class AsyncTemplatesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTemplatesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTemplatesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTemplatesClient
        """
        return self._raw_client

    async def save_notebook_as_template(
        self,
        notebook_id: int,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        output_type: typing.Optional[TemplateFromNotebookCreateOutputType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TemplateRead:
        """
        Parameters
        ----------
        notebook_id : int

        name : str

        description : typing.Optional[str]

        output_type : typing.Optional[TemplateFromNotebookCreateOutputType]
            Preferred default output type for the template.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TemplateRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.templates.save_notebook_as_template(
                notebook_id=1,
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.save_notebook_as_template(
            notebook_id, name=name, description=description, output_type=output_type, request_options=request_options
        )
        return _response.data

    async def list_templates(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TemplateRead]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TemplateRead]
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.templates.list_templates()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_templates(request_options=request_options)
        return _response.data

    async def create_template(
        self,
        *,
        config_json: TemplateConfigInput,
        name: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TemplateRead:
        """
        Parameters
        ----------
        config_json : TemplateConfigInput

        name : str

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TemplateRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient, TemplateConfigInput

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.templates.create_template(
                config_json=TemplateConfigInput(),
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_template(
            config_json=config_json, name=name, description=description, request_options=request_options
        )
        return _response.data

    async def get_template(
        self, template_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TemplateRead:
        """
        Parameters
        ----------
        template_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TemplateRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.templates.get_template(
                template_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_template(template_id, request_options=request_options)
        return _response.data

    async def delete_template(
        self, template_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        template_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.templates.delete_template(
                template_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_template(template_id, request_options=request_options)
        return _response.data

    async def update_template(
        self,
        template_id: int,
        *,
        config_json: typing.Optional[TemplateConfigInput] = OMIT,
        description: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TemplateRead:
        """
        Parameters
        ----------
        template_id : int

        config_json : typing.Optional[TemplateConfigInput]

        description : typing.Optional[str]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TemplateRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.templates.update_template(
                template_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_template(
            template_id, config_json=config_json, description=description, name=name, request_options=request_options
        )
        return _response.data
