default:
    @just -l

install:
    pnpm install

dev:
    if [ ! -x node_modules/.bin/vite ]; then pnpm install; fi
    pnpm dev

preview:
    pnpm preview

build:
    pnpm run build

test:
    pnpm test
