default:
    @just -l

install:
    pnpm install

ensure-deps:
    if [ ! -f node_modules/.modules.yaml ] || [ pnpm-lock.yaml -nt node_modules/.modules.yaml ]; then pnpm install; fi

dev: ensure-deps
    pnpm dev

preview: ensure-deps
    pnpm preview

build: ensure-deps
    pnpm run build

test: ensure-deps
    pnpm test
