# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .analysis_result import AnalysisResult
    from .chunk_read import ChunkRead
    from .citation import Citation
    from .config_option import ConfigOption
    from .context_stats_response import ContextStatsResponse
    from .convert_session_to_output_response import ConvertSessionToOutputResponse
    from .convert_session_to_source_response import ConvertSessionToSourceResponse
    from .convert_source_qa_to_source_response import ConvertSourceQaToSourceResponse
    from .convert_to_source_response import ConvertToSourceResponse
    from .export_research_response import ExportResearchResponse
    from .extractor_info_response import ExtractorInfoResponse
    from .extractors_list_response import ExtractorsListResponse
    from .http_validation_error import HttpValidationError
    from .message_read import MessageRead
    from .message_read_role import MessageReadRole
    from .model_read import ModelRead
    from .model_read_provider import ModelReadProvider
    from .models_list_response import ModelsListResponse
    from .notebook_read import NotebookRead
    from .output_read import OutputRead
    from .output_read_type import OutputReadType
    from .output_type_input import OutputTypeInput
    from .output_type_output import OutputTypeOutput
    from .qa_message import QaMessage
    from .qa_message_role import QaMessageRole
    from .qa_request import QaRequest
    from .qa_response import QaResponse
    from .refine_batch_output import RefineBatchOutput
    from .refine_batch_response import RefineBatchResponse
    from .refine_response import RefineResponse
    from .relation import Relation
    from .relation_relation_type import RelationRelationType
    from .research_session_list_item import ResearchSessionListItem
    from .research_session_list_item_status import ResearchSessionListItemStatus
    from .research_session_response import ResearchSessionResponse
    from .research_session_response_status import ResearchSessionResponseStatus
    from .research_status import ResearchStatus
    from .research_step_response import ResearchStepResponse
    from .research_step_response_status import ResearchStepResponseStatus
    from .research_step_response_type import ResearchStepResponseType
    from .research_step_status import ResearchStepStatus
    from .research_step_type import ResearchStepType
    from .search_plan import SearchPlan
    from .search_query import SearchQuery
    from .session_read import SessionRead
    from .slide_draft_read import SlideDraftRead
    from .slide_draft_read_stage import SlideDraftReadStage
    from .slide_draft_read_status import SlideDraftReadStatus
    from .slide_generation_config import SlideGenerationConfig
    from .slide_outline import SlideOutline
    from .slide_outline_item import SlideOutlineItem
    from .slide_stage import SlideStage
    from .slide_status import SlideStatus
    from .slides_config_option import SlidesConfigOption
    from .slides_config_response import SlidesConfigResponse
    from .slides_theme_preset import SlidesThemePreset
    from .source_batch_delete_response import SourceBatchDeleteResponse
    from .source_from_url_mode import SourceFromUrlMode
    from .source_qa_response import SourceQaResponse
    from .source_read import SourceRead
    from .source_read_status import SourceReadStatus
    from .source_search_response import SourceSearchResponse
    from .source_search_response_status import SourceSearchResponseStatus
    from .source_search_result import SourceSearchResult
    from .source_search_status import SourceSearchStatus
    from .source_status import SourceStatus
    from .source_summary_response import SourceSummaryResponse
    from .structured_refine import StructuredRefine
    from .task_read import TaskRead
    from .task_read_status import TaskReadStatus
    from .task_read_type import TaskReadType
    from .task_status import TaskStatus
    from .task_type import TaskType
    from .tool_config_response import ToolConfigResponse
    from .topic import Topic
    from .validation_error import ValidationError
    from .validation_error_loc_item import ValidationErrorLocItem
    from .workspace_tool import WorkspaceTool
    from .workspace_tool_output_type import WorkspaceToolOutputType
    from .workspace_tool_tone import WorkspaceToolTone
    from .workspace_tools_response import WorkspaceToolsResponse
_dynamic_imports: typing.Dict[str, str] = {
    "AnalysisResult": ".analysis_result",
    "ChunkRead": ".chunk_read",
    "Citation": ".citation",
    "ConfigOption": ".config_option",
    "ContextStatsResponse": ".context_stats_response",
    "ConvertSessionToOutputResponse": ".convert_session_to_output_response",
    "ConvertSessionToSourceResponse": ".convert_session_to_source_response",
    "ConvertSourceQaToSourceResponse": ".convert_source_qa_to_source_response",
    "ConvertToSourceResponse": ".convert_to_source_response",
    "ExportResearchResponse": ".export_research_response",
    "ExtractorInfoResponse": ".extractor_info_response",
    "ExtractorsListResponse": ".extractors_list_response",
    "HttpValidationError": ".http_validation_error",
    "MessageRead": ".message_read",
    "MessageReadRole": ".message_read_role",
    "ModelRead": ".model_read",
    "ModelReadProvider": ".model_read_provider",
    "ModelsListResponse": ".models_list_response",
    "NotebookRead": ".notebook_read",
    "OutputRead": ".output_read",
    "OutputReadType": ".output_read_type",
    "OutputTypeInput": ".output_type_input",
    "OutputTypeOutput": ".output_type_output",
    "QaMessage": ".qa_message",
    "QaMessageRole": ".qa_message_role",
    "QaRequest": ".qa_request",
    "QaResponse": ".qa_response",
    "RefineBatchOutput": ".refine_batch_output",
    "RefineBatchResponse": ".refine_batch_response",
    "RefineResponse": ".refine_response",
    "Relation": ".relation",
    "RelationRelationType": ".relation_relation_type",
    "ResearchSessionListItem": ".research_session_list_item",
    "ResearchSessionListItemStatus": ".research_session_list_item_status",
    "ResearchSessionResponse": ".research_session_response",
    "ResearchSessionResponseStatus": ".research_session_response_status",
    "ResearchStatus": ".research_status",
    "ResearchStepResponse": ".research_step_response",
    "ResearchStepResponseStatus": ".research_step_response_status",
    "ResearchStepResponseType": ".research_step_response_type",
    "ResearchStepStatus": ".research_step_status",
    "ResearchStepType": ".research_step_type",
    "SearchPlan": ".search_plan",
    "SearchQuery": ".search_query",
    "SessionRead": ".session_read",
    "SlideDraftRead": ".slide_draft_read",
    "SlideDraftReadStage": ".slide_draft_read_stage",
    "SlideDraftReadStatus": ".slide_draft_read_status",
    "SlideGenerationConfig": ".slide_generation_config",
    "SlideOutline": ".slide_outline",
    "SlideOutlineItem": ".slide_outline_item",
    "SlideStage": ".slide_stage",
    "SlideStatus": ".slide_status",
    "SlidesConfigOption": ".slides_config_option",
    "SlidesConfigResponse": ".slides_config_response",
    "SlidesThemePreset": ".slides_theme_preset",
    "SourceBatchDeleteResponse": ".source_batch_delete_response",
    "SourceFromUrlMode": ".source_from_url_mode",
    "SourceQaResponse": ".source_qa_response",
    "SourceRead": ".source_read",
    "SourceReadStatus": ".source_read_status",
    "SourceSearchResponse": ".source_search_response",
    "SourceSearchResponseStatus": ".source_search_response_status",
    "SourceSearchResult": ".source_search_result",
    "SourceSearchStatus": ".source_search_status",
    "SourceStatus": ".source_status",
    "SourceSummaryResponse": ".source_summary_response",
    "StructuredRefine": ".structured_refine",
    "TaskRead": ".task_read",
    "TaskReadStatus": ".task_read_status",
    "TaskReadType": ".task_read_type",
    "TaskStatus": ".task_status",
    "TaskType": ".task_type",
    "ToolConfigResponse": ".tool_config_response",
    "Topic": ".topic",
    "ValidationError": ".validation_error",
    "ValidationErrorLocItem": ".validation_error_loc_item",
    "WorkspaceTool": ".workspace_tool",
    "WorkspaceToolOutputType": ".workspace_tool_output_type",
    "WorkspaceToolTone": ".workspace_tool_tone",
    "WorkspaceToolsResponse": ".workspace_tools_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AnalysisResult",
    "ChunkRead",
    "Citation",
    "ConfigOption",
    "ContextStatsResponse",
    "ConvertSessionToOutputResponse",
    "ConvertSessionToSourceResponse",
    "ConvertSourceQaToSourceResponse",
    "ConvertToSourceResponse",
    "ExportResearchResponse",
    "ExtractorInfoResponse",
    "ExtractorsListResponse",
    "HttpValidationError",
    "MessageRead",
    "MessageReadRole",
    "ModelRead",
    "ModelReadProvider",
    "ModelsListResponse",
    "NotebookRead",
    "OutputRead",
    "OutputReadType",
    "OutputTypeInput",
    "OutputTypeOutput",
    "QaMessage",
    "QaMessageRole",
    "QaRequest",
    "QaResponse",
    "RefineBatchOutput",
    "RefineBatchResponse",
    "RefineResponse",
    "Relation",
    "RelationRelationType",
    "ResearchSessionListItem",
    "ResearchSessionListItemStatus",
    "ResearchSessionResponse",
    "ResearchSessionResponseStatus",
    "ResearchStatus",
    "ResearchStepResponse",
    "ResearchStepResponseStatus",
    "ResearchStepResponseType",
    "ResearchStepStatus",
    "ResearchStepType",
    "SearchPlan",
    "SearchQuery",
    "SessionRead",
    "SlideDraftRead",
    "SlideDraftReadStage",
    "SlideDraftReadStatus",
    "SlideGenerationConfig",
    "SlideOutline",
    "SlideOutlineItem",
    "SlideStage",
    "SlideStatus",
    "SlidesConfigOption",
    "SlidesConfigResponse",
    "SlidesThemePreset",
    "SourceBatchDeleteResponse",
    "SourceFromUrlMode",
    "SourceQaResponse",
    "SourceRead",
    "SourceReadStatus",
    "SourceSearchResponse",
    "SourceSearchResponseStatus",
    "SourceSearchResult",
    "SourceSearchStatus",
    "SourceStatus",
    "SourceSummaryResponse",
    "StructuredRefine",
    "TaskRead",
    "TaskReadStatus",
    "TaskReadType",
    "TaskStatus",
    "TaskType",
    "ToolConfigResponse",
    "Topic",
    "ValidationError",
    "ValidationErrorLocItem",
    "WorkspaceTool",
    "WorkspaceToolOutputType",
    "WorkspaceToolTone",
    "WorkspaceToolsResponse",
]
