# This file was auto-generated by Fern from our API Definition.

import typing

FieldDescriptorType = typing.Union[
    typing.Literal["text", "heading", "badge", "list", "tree", "date", "citation", "code"], typing.Any
]
