# This file was auto-generated by Fern from our API Definition.

import typing

OutputReadType = typing.Union[
    typing.Literal[
        "FAQ", "GUIDE", "TIMELINE", "MINDMAP", "QUIZ", "BRIEFING", "SLIDES", "PARAGRAPH", "BULLETS", "STRUCTURED"
    ],
    typing.Any,
]
