# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .citation import Citation
from .context_stats_response import ContextStatsResponse


class QaResponse(UniversalBaseModel):
    answer: str
    citations: typing.List[Citation]
    evidence: bool
    confidence: float
    created_at: dt.datetime
    context: ContextStatsResponse

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
