# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .citation import Citation
from .structured_refine import StructuredRefine


class RefineResponse(UniversalBaseModel):
    bullets: typing.Optional[typing.List[str]] = None
    citations: typing.List[Citation]
    created_at: dt.datetime
    evidence: bool
    format: str
    paragraph: typing.Optional[str] = None
    structured: typing.Optional[StructuredRefine] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
