# This file was auto-generated by Fern from our API Definition.

import typing

RenderDescriptorLayout = typing.Union[
    typing.Literal["list", "cards", "tree", "timeline", "sections", "table"], typing.Any
]
