# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .research_session_response_status import ResearchSessionResponseStatus
from .research_step_response import ResearchStepResponse


class ResearchSessionResponse(UniversalBaseModel):
    """
    Response model for a research session.
    """

    id: int
    notebook_id: int
    topic: str
    status: ResearchSessionResponseStatus = pydantic.Field()
    """
    枚举值:

    * `planning`: 正在规划搜索
    * `searching`: 正在执行搜索
    * `analyzing`: 正在分析结果
    * `waiting_user`: 等待用户确认
    * `completed`: 研究完成
    * `cancelled`: 已取消
    """

    current_iteration: int
    max_iterations: int
    aggregated_results: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None
    final_report: typing.Optional[str] = None
    created_at: dt.datetime
    updated_at: dt.datetime
    steps: typing.Optional[typing.List[ResearchStepResponse]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
