# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .research_session_list_item_status import ResearchSessionListItemStatus


class ResearchSessionListItem(UniversalBaseModel):
    """
    Simplified response for listing research sessions.
    """

    created_at: dt.datetime
    current_iteration: int
    id: int
    max_iterations: int
    notebook_id: int
    result_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of aggregated results
    """

    status: ResearchSessionListItemStatus = pydantic.Field()
    """
    枚举值:

    * `planning`: 正在规划搜索
    * `searching`: 正在执行搜索
    * `analyzing`: 正在分析结果
    * `waiting_user`: 等待用户确认
    * `completed`: 研究完成
    * `cancelled`: 已取消
    """

    topic: str
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
