# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SearchQuery(UniversalBaseModel):
    """
    A single search query in a search plan.
    """

    query: str = pydantic.Field()
    """
    Search query string
    """

    engine: typing.Optional[str] = pydantic.Field(default=None)
    """
    Search engine: Web, Scholar, Docs
    """

    priority: typing.Optional[int] = pydantic.Field(default=None)
    """
    Priority: 1=high, 2=medium, 3=low
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Reason for this query
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
