# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .search_query import SearchQuery


class SearchPlan(UniversalBaseModel):
    """
    A search plan for one iteration.
    """

    iteration: int = pydantic.Field()
    """
    Iteration number
    """

    queries: typing.Optional[typing.List[SearchQuery]] = pydantic.Field(default=None)
    """
    Queries to execute
    """

    reasoning: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent reasoning for this plan
    """

    estimated_results: typing.Optional[int] = pydantic.Field(default=None)
    """
    Estimated number of results
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
