# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .slide_draft_read_stage import SlideDraftReadStage
from .slide_draft_read_status import SlideDraftReadStatus
from .slide_generation_config import SlideGenerationConfig
from .slide_outline import SlideOutline


class SlideDraftRead(UniversalBaseModel):
    id: int
    notebook_id: int
    output_id: typing.Optional[int] = None
    title: typing.Optional[str] = None
    prompt: typing.Optional[str] = None
    engine: str
    chunk_ids: typing.Optional[typing.List[int]] = None
    outline: typing.Optional[SlideOutline] = None
    markdown: typing.Optional[str] = None
    generation_config: typing.Optional[SlideGenerationConfig] = None
    stage: SlideDraftReadStage = pydantic.Field()
    """
    枚举值:

    * `input`: 输入阶段
    * `outline`: 大纲阶段
    * `markdown`: Markdown 阶段
    """

    status: SlideDraftReadStatus = pydantic.Field()
    """
    枚举值:

    * `idle`: 空闲
    * `running`: 生成中
    * `error`: 失败
    """

    error_message: typing.Optional[str] = None
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
