# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .source_search_response_status import SourceSearchResponseStatus
from .source_search_result import SourceSearchResult


class SourceSearchResponse(UniversalBaseModel):
    created_at: dt.datetime
    engine: str
    message: typing.Optional[str] = None
    mode: str
    query: str
    results: typing.List[SourceSearchResult]
    status: SourceSearchResponseStatus = pydantic.Field()
    """
    枚举值:

    * `ok`: 搜索成功
    * `not_implemented`: 功能未实现
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
