# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .source_read_status import SourceReadStatus


class SourceRead(UniversalBaseModel):
    id: int
    notebook_id: int
    filename: str
    mime_type: typing.Optional[str] = None
    parser_type: str
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    status: SourceReadStatus = pydantic.Field()
    """
    枚举值:

    * `processing`: 正在处理
    * `ready`: 处理完成
    * `failed`: 处理失败
    """

    error_message: typing.Optional[str] = None
    chunk_count: typing.Optional[int] = None
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
