# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .crystalith_features_workspace_api_config_option import CrystalithFeaturesWorkspaceApiConfigOption


class ToolConfigResponse(UniversalBaseModel):
    """
    Configuration options for a specific tool.
    """

    difficulty_options: typing.Optional[typing.List[CrystalithFeaturesWorkspaceApiConfigOption]] = None
    quantity_options: typing.Optional[typing.List[CrystalithFeaturesWorkspaceApiConfigOption]] = None
    supports_topic: typing.Optional[bool] = None
    tool_id: str
    tool_label: str
    topic_placeholder: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
