# This file was auto-generated by Fern from our API Definition.

import typing

WorkspaceToolTone = typing.Union[
    typing.Literal["slate", "blue", "green", "rose", "amber", "teal", "indigo"], typing.Any
]
