# This file was auto-generated by Fern from our API Definition.

import typing

TemplateFromNotebookCreateOutputType = typing.Union[
    typing.Literal[
        "BRIEFING", "BULLETS", "FAQ", "GUIDE", "MINDMAP", "PARAGRAPH", "QUIZ", "SLIDES", "STRUCTURED", "TIMELINE"
    ],
    typing.Any,
]
