# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.export_research_response import ExportResearchResponse
from ..types.research_session_list_item import ResearchSessionListItem
from ..types.research_session_response import ResearchSessionResponse
from ..types.search_plan import SearchPlan
from .raw_client import AsyncRawResearchClient, RawResearchClient
from .types.list_research_sessions_v1notebooks_notebook_id_research_get_request_status import (
    ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ResearchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawResearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawResearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawResearchClient
        """
        return self._raw_client

    def list_research_sessions(
        self,
        notebook_id: int,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        status: typing.Optional[ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ResearchSessionListItem]:
        """
        List research sessions for a notebook.

        Parameters
        ----------
        notebook_id : int

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        status : typing.Optional[ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus]
            枚举值:

            * `planning`: 正在规划搜索
            * `searching`: 正在执行搜索
            * `analyzing`: 正在分析结果
            * `waiting_user`: 等待用户确认
            * `completed`: 研究完成
            * `cancelled`: 已取消

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ResearchSessionListItem]
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.list_research_sessions(
            notebook_id=1,
        )
        """
        _response = self._raw_client.list_research_sessions(
            notebook_id, offset=offset, limit=limit, status=status, request_options=request_options
        )
        return _response.data

    def create_research_session(
        self,
        notebook_id: int,
        *,
        topic: str,
        max_iterations: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResearchSessionResponse:
        """
        Create a new deep research session.

        Parameters
        ----------
        notebook_id : int

        topic : str
            Research topic

        max_iterations : typing.Optional[int]
            Maximum iterations

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.create_research_session(
            notebook_id=1,
            topic="topic",
        )
        """
        _response = self._raw_client.create_research_session(
            notebook_id, topic=topic, max_iterations=max_iterations, request_options=request_options
        )
        return _response.data

    def get_research_session(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Get details of a research session including all steps.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.get_research_session(
            notebook_id=1,
            research_id=1,
        )
        """
        _response = self._raw_client.get_research_session(notebook_id, research_id, request_options=request_options)
        return _response.data

    def delete_research_session(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete or cancel a research session.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.delete_research_session(
            notebook_id=1,
            research_id=1,
        )
        """
        _response = self._raw_client.delete_research_session(notebook_id, research_id, request_options=request_options)
        return _response.data

    def approve_search_plan(
        self,
        notebook_id: int,
        research_id: int,
        *,
        feedback: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResearchSessionResponse:
        """
        Approve the current search plan and continue research.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        feedback : typing.Optional[str]
            Optional feedback on the plan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.approve_search_plan(
            notebook_id=1,
            research_id=1,
        )
        """
        _response = self._raw_client.approve_search_plan(
            notebook_id, research_id, feedback=feedback, request_options=request_options
        )
        return _response.data

    def modify_search_plan(
        self,
        notebook_id: int,
        research_id: int,
        *,
        plan: SearchPlan,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResearchSessionResponse:
        """
        Modify the current search plan.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        plan : SearchPlan
            Modified search plan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient, SearchPlan

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.modify_search_plan(
            notebook_id=1,
            research_id=1,
            plan=SearchPlan(
                iteration=1,
            ),
        )
        """
        _response = self._raw_client.modify_search_plan(
            notebook_id, research_id, plan=plan, request_options=request_options
        )
        return _response.data

    def skip_iteration(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Skip the current iteration.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.skip_iteration(
            notebook_id=1,
            research_id=1,
        )
        """
        _response = self._raw_client.skip_iteration(notebook_id, research_id, request_options=request_options)
        return _response.data

    def finish_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Finish research early and generate report.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.finish_research(
            notebook_id=1,
            research_id=1,
        )
        """
        _response = self._raw_client.finish_research(notebook_id, research_id, request_options=request_options)
        return _response.data

    def cancel_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Cancel an ongoing research session.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.cancel_research(
            notebook_id=1,
            research_id=1,
        )
        """
        _response = self._raw_client.cancel_research(notebook_id, research_id, request_options=request_options)
        return _response.data

    def resume_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Resume a cancelled research session.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.resume_research(
            notebook_id=1,
            research_id=1,
        )
        """
        _response = self._raw_client.resume_research(notebook_id, research_id, request_options=request_options)
        return _response.data

    def start_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Start executing the research graph.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.start_research(
            notebook_id=1,
            research_id=1,
        )
        """
        _response = self._raw_client.start_research(notebook_id, research_id, request_options=request_options)
        return _response.data

    def stream_research_progress(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Stream research progress using Server-Sent Events.

        Events:
        - `status`: Status update `{"status": "...", "iteration": n}`
        - `plan_ready`: Search plan ready `{"plan": {...}}`
        - `search_progress`: Search progress `{"query": "...", "completed": n, "total": m}`
        - `search_result`: New result `{"title": "...", "url": "..."}`
        - `analysis`: Analysis complete `{"summary": "...", "coverage": 0.x}`
        - `report`: Final report `{"report": "..."}`
        - `done`: Research complete `{"total_results": n}`
        - `error`: Error `{"message": "..."}`

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            SSE stream of research progress

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.stream_research_progress(
            notebook_id=1,
            research_id=1,
        )
        """
        _response = self._raw_client.stream_research_progress(notebook_id, research_id, request_options=request_options)
        return _response.data

    def export_research(
        self,
        notebook_id: int,
        research_id: int,
        *,
        export_type: typing.Optional[str] = OMIT,
        include_report: typing.Optional[bool] = OMIT,
        include_results: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExportResearchResponse:
        """
        Export research report to a source or note.

        - export_type='source': Creates a new markdown source with the report
        - export_type='note': Creates a new note (output) with the report

        Parameters
        ----------
        notebook_id : int

        research_id : int

        export_type : typing.Optional[str]
            Export type: 'source' or 'note'

        include_report : typing.Optional[bool]
            Include final report

        include_results : typing.Optional[bool]
            Include aggregated results as links

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExportResearchResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.research.export_research(
            notebook_id=1,
            research_id=1,
        )
        """
        _response = self._raw_client.export_research(
            notebook_id,
            research_id,
            export_type=export_type,
            include_report=include_report,
            include_results=include_results,
            request_options=request_options,
        )
        return _response.data


class AsyncResearchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawResearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawResearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawResearchClient
        """
        return self._raw_client

    async def list_research_sessions(
        self,
        notebook_id: int,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        status: typing.Optional[ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[ResearchSessionListItem]:
        """
        List research sessions for a notebook.

        Parameters
        ----------
        notebook_id : int

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        status : typing.Optional[ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus]
            枚举值:

            * `planning`: 正在规划搜索
            * `searching`: 正在执行搜索
            * `analyzing`: 正在分析结果
            * `waiting_user`: 等待用户确认
            * `completed`: 研究完成
            * `cancelled`: 已取消

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ResearchSessionListItem]
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.list_research_sessions(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_research_sessions(
            notebook_id, offset=offset, limit=limit, status=status, request_options=request_options
        )
        return _response.data

    async def create_research_session(
        self,
        notebook_id: int,
        *,
        topic: str,
        max_iterations: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResearchSessionResponse:
        """
        Create a new deep research session.

        Parameters
        ----------
        notebook_id : int

        topic : str
            Research topic

        max_iterations : typing.Optional[int]
            Maximum iterations

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.create_research_session(
                notebook_id=1,
                topic="topic",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_research_session(
            notebook_id, topic=topic, max_iterations=max_iterations, request_options=request_options
        )
        return _response.data

    async def get_research_session(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Get details of a research session including all steps.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.get_research_session(
                notebook_id=1,
                research_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_research_session(
            notebook_id, research_id, request_options=request_options
        )
        return _response.data

    async def delete_research_session(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete or cancel a research session.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.delete_research_session(
                notebook_id=1,
                research_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_research_session(
            notebook_id, research_id, request_options=request_options
        )
        return _response.data

    async def approve_search_plan(
        self,
        notebook_id: int,
        research_id: int,
        *,
        feedback: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResearchSessionResponse:
        """
        Approve the current search plan and continue research.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        feedback : typing.Optional[str]
            Optional feedback on the plan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.approve_search_plan(
                notebook_id=1,
                research_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.approve_search_plan(
            notebook_id, research_id, feedback=feedback, request_options=request_options
        )
        return _response.data

    async def modify_search_plan(
        self,
        notebook_id: int,
        research_id: int,
        *,
        plan: SearchPlan,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResearchSessionResponse:
        """
        Modify the current search plan.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        plan : SearchPlan
            Modified search plan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient, SearchPlan

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.modify_search_plan(
                notebook_id=1,
                research_id=1,
                plan=SearchPlan(
                    iteration=1,
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.modify_search_plan(
            notebook_id, research_id, plan=plan, request_options=request_options
        )
        return _response.data

    async def skip_iteration(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Skip the current iteration.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.skip_iteration(
                notebook_id=1,
                research_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.skip_iteration(notebook_id, research_id, request_options=request_options)
        return _response.data

    async def finish_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Finish research early and generate report.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.finish_research(
                notebook_id=1,
                research_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.finish_research(notebook_id, research_id, request_options=request_options)
        return _response.data

    async def cancel_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Cancel an ongoing research session.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.cancel_research(
                notebook_id=1,
                research_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_research(notebook_id, research_id, request_options=request_options)
        return _response.data

    async def resume_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Resume a cancelled research session.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.resume_research(
                notebook_id=1,
                research_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resume_research(notebook_id, research_id, request_options=request_options)
        return _response.data

    async def start_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ResearchSessionResponse:
        """
        Start executing the research graph.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResearchSessionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.start_research(
                notebook_id=1,
                research_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_research(notebook_id, research_id, request_options=request_options)
        return _response.data

    async def stream_research_progress(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Stream research progress using Server-Sent Events.

        Events:
        - `status`: Status update `{"status": "...", "iteration": n}`
        - `plan_ready`: Search plan ready `{"plan": {...}}`
        - `search_progress`: Search progress `{"query": "...", "completed": n, "total": m}`
        - `search_result`: New result `{"title": "...", "url": "..."}`
        - `analysis`: Analysis complete `{"summary": "...", "coverage": 0.x}`
        - `report`: Final report `{"report": "..."}`
        - `done`: Research complete `{"total_results": n}`
        - `error`: Error `{"message": "..."}`

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            SSE stream of research progress

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.stream_research_progress(
                notebook_id=1,
                research_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stream_research_progress(
            notebook_id, research_id, request_options=request_options
        )
        return _response.data

    async def export_research(
        self,
        notebook_id: int,
        research_id: int,
        *,
        export_type: typing.Optional[str] = OMIT,
        include_report: typing.Optional[bool] = OMIT,
        include_results: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExportResearchResponse:
        """
        Export research report to a source or note.

        - export_type='source': Creates a new markdown source with the report
        - export_type='note': Creates a new note (output) with the report

        Parameters
        ----------
        notebook_id : int

        research_id : int

        export_type : typing.Optional[str]
            Export type: 'source' or 'note'

        include_report : typing.Optional[bool]
            Include final report

        include_results : typing.Optional[bool]
            Include aggregated results as links

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExportResearchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.research.export_research(
                notebook_id=1,
                research_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.export_research(
            notebook_id,
            research_id,
            export_type=export_type,
            include_report=include_report,
            include_results=include_results,
            request_options=request_options,
        )
        return _response.data
