# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.export_research_response import ExportResearchResponse
from ..types.http_validation_error import HttpValidationError
from ..types.research_session_list_item import ResearchSessionListItem
from ..types.research_session_response import ResearchSessionResponse
from ..types.search_plan import SearchPlan
from .types.list_research_sessions_v1notebooks_notebook_id_research_get_request_status import (
    ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawResearchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_research_sessions(
        self,
        notebook_id: int,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        status: typing.Optional[ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[ResearchSessionListItem]]:
        """
        List research sessions for a notebook.

        Parameters
        ----------
        notebook_id : int

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        status : typing.Optional[ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus]
            枚举值:

            * `planning`: 正在规划搜索
            * `searching`: 正在执行搜索
            * `analyzing`: 正在分析结果
            * `waiting_user`: 等待用户确认
            * `completed`: 研究完成
            * `cancelled`: 已取消

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[ResearchSessionListItem]]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research",
            method="GET",
            params={
                "offset": offset,
                "limit": limit,
                "status": status,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[ResearchSessionListItem],
                    parse_obj_as(
                        type_=typing.List[ResearchSessionListItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_research_session(
        self,
        notebook_id: int,
        *,
        topic: str,
        max_iterations: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ResearchSessionResponse]:
        """
        Create a new deep research session.

        Parameters
        ----------
        notebook_id : int

        topic : str
            Research topic

        max_iterations : typing.Optional[int]
            Maximum iterations

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research",
            method="POST",
            json={
                "topic": topic,
                "max_iterations": max_iterations,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_research_session(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ResearchSessionResponse]:
        """
        Get details of a research session including all steps.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_research_session(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Delete or cancel a research session.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def approve_search_plan(
        self,
        notebook_id: int,
        research_id: int,
        *,
        feedback: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ResearchSessionResponse]:
        """
        Approve the current search plan and continue research.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        feedback : typing.Optional[str]
            Optional feedback on the plan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/approve",
            method="POST",
            json={
                "feedback": feedback,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def modify_search_plan(
        self,
        notebook_id: int,
        research_id: int,
        *,
        plan: SearchPlan,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ResearchSessionResponse]:
        """
        Modify the current search plan.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        plan : SearchPlan
            Modified search plan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/modify",
            method="POST",
            json={
                "plan": convert_and_respect_annotation_metadata(object_=plan, annotation=SearchPlan, direction="write"),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def skip_iteration(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ResearchSessionResponse]:
        """
        Skip the current iteration.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/skip",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def finish_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ResearchSessionResponse]:
        """
        Finish research early and generate report.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/finish",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def cancel_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ResearchSessionResponse]:
        """
        Cancel an ongoing research session.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/cancel",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def start_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ResearchSessionResponse]:
        """
        Start executing the research graph.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/start",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def stream_research_progress(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Any]:
        """
        Stream research progress using Server-Sent Events.

        Events:
        - `status`: Status update `{"status": "...", "iteration": n}`
        - `plan_ready`: Search plan ready `{"plan": {...}}`
        - `search_progress`: Search progress `{"query": "...", "completed": n, "total": m}`
        - `search_result`: New result `{"title": "...", "url": "..."}`
        - `analysis`: Analysis complete `{"summary": "...", "coverage": 0.x}`
        - `report`: Final report `{"report": "..."}`
        - `done`: Research complete `{"total_results": n}`
        - `error`: Error `{"message": "..."}`

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            SSE stream of research progress
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/stream",
            method="GET",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def export_research(
        self,
        notebook_id: int,
        research_id: int,
        *,
        export_type: typing.Optional[str] = OMIT,
        include_report: typing.Optional[bool] = OMIT,
        include_results: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ExportResearchResponse]:
        """
        Export research report to a source or note.

        - export_type='source': Creates a new markdown source with the report
        - export_type='note': Creates a new note (output) with the report

        Parameters
        ----------
        notebook_id : int

        research_id : int

        export_type : typing.Optional[str]
            Export type: 'source' or 'note'

        include_report : typing.Optional[bool]
            Include final report

        include_results : typing.Optional[bool]
            Include aggregated results as links

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ExportResearchResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/export",
            method="POST",
            json={
                "export_type": export_type,
                "include_report": include_report,
                "include_results": include_results,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExportResearchResponse,
                    parse_obj_as(
                        type_=ExportResearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawResearchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_research_sessions(
        self,
        notebook_id: int,
        *,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        status: typing.Optional[ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[ResearchSessionListItem]]:
        """
        List research sessions for a notebook.

        Parameters
        ----------
        notebook_id : int

        offset : typing.Optional[int]

        limit : typing.Optional[int]

        status : typing.Optional[ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus]
            枚举值:

            * `planning`: 正在规划搜索
            * `searching`: 正在执行搜索
            * `analyzing`: 正在分析结果
            * `waiting_user`: 等待用户确认
            * `completed`: 研究完成
            * `cancelled`: 已取消

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[ResearchSessionListItem]]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research",
            method="GET",
            params={
                "offset": offset,
                "limit": limit,
                "status": status,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[ResearchSessionListItem],
                    parse_obj_as(
                        type_=typing.List[ResearchSessionListItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_research_session(
        self,
        notebook_id: int,
        *,
        topic: str,
        max_iterations: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ResearchSessionResponse]:
        """
        Create a new deep research session.

        Parameters
        ----------
        notebook_id : int

        topic : str
            Research topic

        max_iterations : typing.Optional[int]
            Maximum iterations

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research",
            method="POST",
            json={
                "topic": topic,
                "max_iterations": max_iterations,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_research_session(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ResearchSessionResponse]:
        """
        Get details of a research session including all steps.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_research_session(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Delete or cancel a research session.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def approve_search_plan(
        self,
        notebook_id: int,
        research_id: int,
        *,
        feedback: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ResearchSessionResponse]:
        """
        Approve the current search plan and continue research.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        feedback : typing.Optional[str]
            Optional feedback on the plan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/approve",
            method="POST",
            json={
                "feedback": feedback,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def modify_search_plan(
        self,
        notebook_id: int,
        research_id: int,
        *,
        plan: SearchPlan,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ResearchSessionResponse]:
        """
        Modify the current search plan.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        plan : SearchPlan
            Modified search plan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/modify",
            method="POST",
            json={
                "plan": convert_and_respect_annotation_metadata(object_=plan, annotation=SearchPlan, direction="write"),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def skip_iteration(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ResearchSessionResponse]:
        """
        Skip the current iteration.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/skip",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def finish_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ResearchSessionResponse]:
        """
        Finish research early and generate report.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/finish",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def cancel_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ResearchSessionResponse]:
        """
        Cancel an ongoing research session.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/cancel",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def start_research(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ResearchSessionResponse]:
        """
        Start executing the research graph.

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ResearchSessionResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/start",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ResearchSessionResponse,
                    parse_obj_as(
                        type_=ResearchSessionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def stream_research_progress(
        self, notebook_id: int, research_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Stream research progress using Server-Sent Events.

        Events:
        - `status`: Status update `{"status": "...", "iteration": n}`
        - `plan_ready`: Search plan ready `{"plan": {...}}`
        - `search_progress`: Search progress `{"query": "...", "completed": n, "total": m}`
        - `search_result`: New result `{"title": "...", "url": "..."}`
        - `analysis`: Analysis complete `{"summary": "...", "coverage": 0.x}`
        - `report`: Final report `{"report": "..."}`
        - `done`: Research complete `{"total_results": n}`
        - `error`: Error `{"message": "..."}`

        Parameters
        ----------
        notebook_id : int

        research_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            SSE stream of research progress
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/stream",
            method="GET",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def export_research(
        self,
        notebook_id: int,
        research_id: int,
        *,
        export_type: typing.Optional[str] = OMIT,
        include_report: typing.Optional[bool] = OMIT,
        include_results: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ExportResearchResponse]:
        """
        Export research report to a source or note.

        - export_type='source': Creates a new markdown source with the report
        - export_type='note': Creates a new note (output) with the report

        Parameters
        ----------
        notebook_id : int

        research_id : int

        export_type : typing.Optional[str]
            Export type: 'source' or 'note'

        include_report : typing.Optional[bool]
            Include final report

        include_results : typing.Optional[bool]
            Include aggregated results as links

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ExportResearchResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/research/{jsonable_encoder(research_id)}/export",
            method="POST",
            json={
                "export_type": export_type,
                "include_report": include_report,
                "include_results": include_results,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExportResearchResponse,
                    parse_obj_as(
                        type_=ExportResearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
