# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.refine_batch_response import RefineBatchResponse
from ..types.refine_response import RefineResponse
from .raw_client import AsyncRawRefineClient, RawRefineClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RefineClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRefineClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRefineClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRefineClient
        """
        return self._raw_client

    def refine(
        self,
        notebook_id: int,
        *,
        prompt: str,
        format: typing.Optional[str] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        min_score: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RefineResponse:
        """
        Parameters
        ----------
        notebook_id : int

        prompt : str

        format : typing.Optional[str]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        min_score : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RefineResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.refine.refine(
            notebook_id=1,
            prompt="prompt",
        )
        """
        _response = self._raw_client.refine(
            notebook_id,
            prompt=prompt,
            format=format,
            source_ids=source_ids,
            top_k=top_k,
            min_score=min_score,
            request_options=request_options,
        )
        return _response.data

    def refine_batch(
        self,
        notebook_id: int,
        *,
        prompt: str,
        formats: typing.Optional[typing.Sequence[str]] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        min_score: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RefineBatchResponse:
        """
        Parameters
        ----------
        notebook_id : int

        prompt : str

        formats : typing.Optional[typing.Sequence[str]]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        min_score : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RefineBatchResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.refine.refine_batch(
            notebook_id=1,
            prompt="prompt",
        )
        """
        _response = self._raw_client.refine_batch(
            notebook_id,
            prompt=prompt,
            formats=formats,
            source_ids=source_ids,
            top_k=top_k,
            min_score=min_score,
            request_options=request_options,
        )
        return _response.data


class AsyncRefineClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRefineClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRefineClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRefineClient
        """
        return self._raw_client

    async def refine(
        self,
        notebook_id: int,
        *,
        prompt: str,
        format: typing.Optional[str] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        min_score: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RefineResponse:
        """
        Parameters
        ----------
        notebook_id : int

        prompt : str

        format : typing.Optional[str]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        min_score : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RefineResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.refine.refine(
                notebook_id=1,
                prompt="prompt",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.refine(
            notebook_id,
            prompt=prompt,
            format=format,
            source_ids=source_ids,
            top_k=top_k,
            min_score=min_score,
            request_options=request_options,
        )
        return _response.data

    async def refine_batch(
        self,
        notebook_id: int,
        *,
        prompt: str,
        formats: typing.Optional[typing.Sequence[str]] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        min_score: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RefineBatchResponse:
        """
        Parameters
        ----------
        notebook_id : int

        prompt : str

        formats : typing.Optional[typing.Sequence[str]]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        min_score : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RefineBatchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.refine.refine_batch(
                notebook_id=1,
                prompt="prompt",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.refine_batch(
            notebook_id,
            prompt=prompt,
            formats=formats,
            source_ids=source_ids,
            top_k=top_k,
            min_score=min_score,
            request_options=request_options,
        )
        return _response.data
