# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from ..types.refine_batch_response import RefineBatchResponse
from ..types.refine_response import RefineResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawRefineClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def refine(
        self,
        notebook_id: int,
        *,
        prompt: str,
        format: typing.Optional[str] = OMIT,
        chunk_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        min_score: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RefineResponse]:
        """
        Parameters
        ----------
        notebook_id : int

        prompt : str

        format : typing.Optional[str]

        chunk_ids : typing.Optional[typing.Sequence[int]]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        min_score : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RefineResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/refine",
            method="POST",
            json={
                "prompt": prompt,
                "format": format,
                "chunk_ids": chunk_ids,
                "source_ids": source_ids,
                "top_k": top_k,
                "min_score": min_score,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RefineResponse,
                    parse_obj_as(
                        type_=RefineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def refine_batch(
        self,
        notebook_id: int,
        *,
        prompt: str,
        formats: typing.Optional[typing.Sequence[str]] = OMIT,
        chunk_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        min_score: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RefineBatchResponse]:
        """
        Parameters
        ----------
        notebook_id : int

        prompt : str

        formats : typing.Optional[typing.Sequence[str]]

        chunk_ids : typing.Optional[typing.Sequence[int]]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        min_score : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RefineBatchResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/refine/batch",
            method="POST",
            json={
                "prompt": prompt,
                "formats": formats,
                "chunk_ids": chunk_ids,
                "source_ids": source_ids,
                "top_k": top_k,
                "min_score": min_score,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RefineBatchResponse,
                    parse_obj_as(
                        type_=RefineBatchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawRefineClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def refine(
        self,
        notebook_id: int,
        *,
        prompt: str,
        format: typing.Optional[str] = OMIT,
        chunk_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        min_score: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RefineResponse]:
        """
        Parameters
        ----------
        notebook_id : int

        prompt : str

        format : typing.Optional[str]

        chunk_ids : typing.Optional[typing.Sequence[int]]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        min_score : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RefineResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/refine",
            method="POST",
            json={
                "prompt": prompt,
                "format": format,
                "chunk_ids": chunk_ids,
                "source_ids": source_ids,
                "top_k": top_k,
                "min_score": min_score,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RefineResponse,
                    parse_obj_as(
                        type_=RefineResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def refine_batch(
        self,
        notebook_id: int,
        *,
        prompt: str,
        formats: typing.Optional[typing.Sequence[str]] = OMIT,
        chunk_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        min_score: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RefineBatchResponse]:
        """
        Parameters
        ----------
        notebook_id : int

        prompt : str

        formats : typing.Optional[typing.Sequence[str]]

        chunk_ids : typing.Optional[typing.Sequence[int]]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        min_score : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RefineBatchResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/refine/batch",
            method="POST",
            json={
                "prompt": prompt,
                "formats": formats,
                "chunk_ids": chunk_ids,
                "source_ids": source_ids,
                "top_k": top_k,
                "min_score": min_score,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RefineBatchResponse,
                    parse_obj_as(
                        type_=RefineBatchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
