# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.convert_to_source_response import ConvertToSourceResponse
from ..types.output_read import OutputRead
from .raw_client import AsyncRawOutputsClient, RawOutputsClient
from .types.create_output_v1notebooks_notebook_id_outputs_output_type_post_request_output_type import (
    CreateOutputV1NotebooksNotebookIdOutputsOutputTypePostRequestOutputType,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OutputsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOutputsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOutputsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOutputsClient
        """
        return self._raw_client

    def list_outputs(
        self,
        notebook_id: int,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[OutputRead]:
        """
        Parameters
        ----------
        notebook_id : int

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[OutputRead]
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.outputs.list_outputs(
            notebook_id=1,
        )
        """
        _response = self._raw_client.list_outputs(
            notebook_id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def get_output(
        self, notebook_id: int, output_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OutputRead:
        """
        Parameters
        ----------
        notebook_id : int

        output_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OutputRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.outputs.get_output(
            notebook_id=1,
            output_id=1,
        )
        """
        _response = self._raw_client.get_output(notebook_id, output_id, request_options=request_options)
        return _response.data

    def delete_output(
        self, notebook_id: int, output_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete a specific output by ID.

        Parameters
        ----------
        notebook_id : int

        output_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.outputs.delete_output(
            notebook_id=1,
            output_id=1,
        )
        """
        _response = self._raw_client.delete_output(notebook_id, output_id, request_options=request_options)
        return _response.data

    def convert_output_to_source(
        self, notebook_id: int, output_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ConvertToSourceResponse:
        """
        Convert an output to a source document that can be used for RAG queries.

        Parameters
        ----------
        notebook_id : int

        output_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConvertToSourceResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.outputs.convert_output_to_source(
            notebook_id=1,
            output_id=1,
        )
        """
        _response = self._raw_client.convert_output_to_source(notebook_id, output_id, request_options=request_options)
        return _response.data

    def create_output(
        self,
        notebook_id: int,
        output_type: CreateOutputV1NotebooksNotebookIdOutputsOutputTypePostRequestOutputType,
        *,
        min_score: typing.Optional[float] = OMIT,
        model_id: typing.Optional[str] = OMIT,
        prompt: typing.Optional[str] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OutputRead:
        """
        Parameters
        ----------
        notebook_id : int

        output_type : CreateOutputV1NotebooksNotebookIdOutputsOutputTypePostRequestOutputType
            枚举值:

            * `FAQ`: 问答清单
            * `GUIDE`: 学习/行动指南
            * `TIMELINE`: 关键事件序列
            * `MINDMAP`: 主题层级结构
            * `QUIZ`: 知识检验
            * `BRIEFING`: 高层摘要
            * `SLIDES`: 演示文稿
            * `PARAGRAPH`: 段落摘要
            * `BULLETS`: 要点列表
            * `STRUCTURED`: 结构化摘要

        min_score : typing.Optional[float]

        model_id : typing.Optional[str]
            Optional model ID to use for generation

        prompt : typing.Optional[str]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OutputRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.outputs.create_output(
            notebook_id=1,
            output_type="BRIEFING",
        )
        """
        _response = self._raw_client.create_output(
            notebook_id,
            output_type,
            min_score=min_score,
            model_id=model_id,
            prompt=prompt,
            source_ids=source_ids,
            top_k=top_k,
            request_options=request_options,
        )
        return _response.data


class AsyncOutputsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOutputsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOutputsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOutputsClient
        """
        return self._raw_client

    async def list_outputs(
        self,
        notebook_id: int,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[OutputRead]:
        """
        Parameters
        ----------
        notebook_id : int

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[OutputRead]
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.outputs.list_outputs(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_outputs(
            notebook_id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def get_output(
        self, notebook_id: int, output_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OutputRead:
        """
        Parameters
        ----------
        notebook_id : int

        output_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OutputRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.outputs.get_output(
                notebook_id=1,
                output_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_output(notebook_id, output_id, request_options=request_options)
        return _response.data

    async def delete_output(
        self, notebook_id: int, output_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete a specific output by ID.

        Parameters
        ----------
        notebook_id : int

        output_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.outputs.delete_output(
                notebook_id=1,
                output_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_output(notebook_id, output_id, request_options=request_options)
        return _response.data

    async def convert_output_to_source(
        self, notebook_id: int, output_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ConvertToSourceResponse:
        """
        Convert an output to a source document that can be used for RAG queries.

        Parameters
        ----------
        notebook_id : int

        output_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConvertToSourceResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.outputs.convert_output_to_source(
                notebook_id=1,
                output_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.convert_output_to_source(
            notebook_id, output_id, request_options=request_options
        )
        return _response.data

    async def create_output(
        self,
        notebook_id: int,
        output_type: CreateOutputV1NotebooksNotebookIdOutputsOutputTypePostRequestOutputType,
        *,
        min_score: typing.Optional[float] = OMIT,
        model_id: typing.Optional[str] = OMIT,
        prompt: typing.Optional[str] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OutputRead:
        """
        Parameters
        ----------
        notebook_id : int

        output_type : CreateOutputV1NotebooksNotebookIdOutputsOutputTypePostRequestOutputType
            枚举值:

            * `FAQ`: 问答清单
            * `GUIDE`: 学习/行动指南
            * `TIMELINE`: 关键事件序列
            * `MINDMAP`: 主题层级结构
            * `QUIZ`: 知识检验
            * `BRIEFING`: 高层摘要
            * `SLIDES`: 演示文稿
            * `PARAGRAPH`: 段落摘要
            * `BULLETS`: 要点列表
            * `STRUCTURED`: 结构化摘要

        min_score : typing.Optional[float]

        model_id : typing.Optional[str]
            Optional model ID to use for generation

        prompt : typing.Optional[str]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OutputRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.outputs.create_output(
                notebook_id=1,
                output_type="BRIEFING",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_output(
            notebook_id,
            output_type,
            min_score=min_score,
            model_id=model_id,
            prompt=prompt,
            source_ids=source_ids,
            top_k=top_k,
            request_options=request_options,
        )
        return _response.data
