# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.task_read import TaskRead
from .raw_client import AsyncRawTasksClient, RawTasksClient


class TasksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTasksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTasksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTasksClient
        """
        return self._raw_client

    def list_tasks(
        self, notebook_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TaskRead]:
        """
        Parameters
        ----------
        notebook_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TaskRead]
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.tasks.list_tasks(
            notebook_id=1,
        )
        """
        _response = self._raw_client.list_tasks(notebook_id, request_options=request_options)
        return _response.data

    def get_task(self, task_id: int, *, request_options: typing.Optional[RequestOptions] = None) -> TaskRead:
        """
        Parameters
        ----------
        task_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.tasks.get_task(
            task_id=1,
        )
        """
        _response = self._raw_client.get_task(task_id, request_options=request_options)
        return _response.data

    def cancel_task(self, task_id: int, *, request_options: typing.Optional[RequestOptions] = None) -> TaskRead:
        """
        Parameters
        ----------
        task_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.tasks.cancel_task(
            task_id=1,
        )
        """
        _response = self._raw_client.cancel_task(task_id, request_options=request_options)
        return _response.data


class AsyncTasksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTasksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTasksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTasksClient
        """
        return self._raw_client

    async def list_tasks(
        self, notebook_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[TaskRead]:
        """
        Parameters
        ----------
        notebook_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[TaskRead]
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tasks.list_tasks(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_tasks(notebook_id, request_options=request_options)
        return _response.data

    async def get_task(self, task_id: int, *, request_options: typing.Optional[RequestOptions] = None) -> TaskRead:
        """
        Parameters
        ----------
        task_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tasks.get_task(
                task_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_task(task_id, request_options=request_options)
        return _response.data

    async def cancel_task(self, task_id: int, *, request_options: typing.Optional[RequestOptions] = None) -> TaskRead:
        """
        Parameters
        ----------
        task_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TaskRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tasks.cancel_task(
                task_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_task(task_id, request_options=request_options)
        return _response.data
