# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.analysis_result import AnalysisResult
from .raw_client import AsyncRawAnalysisClient, RawAnalysisClient


class AnalysisClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAnalysisClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAnalysisClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAnalysisClient
        """
        return self._raw_client

    def analyze_notebook(
        self, notebook_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AnalysisResult:
        """
        Parameters
        ----------
        notebook_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnalysisResult
            Successful Response

        Examples
        --------
        from crystalith_sdk import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.analysis.analyze_notebook(
            notebook_id=1,
        )
        """
        _response = self._raw_client.analyze_notebook(notebook_id, request_options=request_options)
        return _response.data


class AsyncAnalysisClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAnalysisClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAnalysisClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAnalysisClient
        """
        return self._raw_client

    async def analyze_notebook(
        self, notebook_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AnalysisResult:
        """
        Parameters
        ----------
        notebook_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnalysisResult
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith_sdk import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.analysis.analyze_notebook(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.analyze_notebook(notebook_id, request_options=request_options)
        return _response.data
