#!/usr/bin/env bash
# Initialize or update local config files from environment variables.
#
# Reads well-known env vars from the user's shell and writes them into:
#   .env              — compose/build parameters
#   config/secrets.yaml — runtime secrets for app.yaml interpolation
#
# Existing values are preserved (env vars only fill in blanks).
# Run via: just upsert-env-configs
#
# Recognized env vars (all optional):
#
#   .env targets:
#     CRYSTALITH_PROFILE             — runtime profile (local|hybrid|docker|full)
#     OPENAI_BASE_URL                — OpenAI-compatible API base URL
#     CRYSTALITH_DEFAULT_EMBEDDING_MODEL — default embedding model ID
#     BRIDGE_FORWARDS                — host-remap bridge forwards
#
#   config/secrets.yaml targets:
#     OPENAI_API_KEY                 — OpenAI API key
#     POSTGRES_PASSWORD              — PostgreSQL password
#     CRYSTALITH_API_KEY             — Crystalith auth API key
#     JINA_API_KEY                   — Jina Reader API key
#     FIRECRAWL_API_KEY              — Firecrawl API key
#     BROWSERLESS_TOKEN              — Browserless token
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

info()  { echo -e "\033[1;34m[init]\033[0m $*"; }
warn()  { echo -e "\033[1;33m[init]\033[0m $*"; }
ok()    { echo -e "\033[1;32m[init]\033[0m $*"; }

# ---------------------------------------------------------------------------
# .env initialization
# ---------------------------------------------------------------------------

ENV_FILE=".env"
ENV_EXAMPLE=".env.example"

init_env_file() {
  if [[ ! -f "$ENV_FILE" ]]; then
    if [[ -f "$ENV_EXAMPLE" ]]; then
      cp "$ENV_EXAMPLE" "$ENV_FILE"
      info "Created $ENV_FILE from $ENV_EXAMPLE"
    else
      touch "$ENV_FILE"
      info "Created empty $ENV_FILE"
    fi
  else
    info "$ENV_FILE already exists, updating..."
  fi

  # Map: SHELL_ENV_VAR -> .env key [-> transform]
  _set_env_var "CRYSTALITH_PROFILE"  "CRYSTALITH_PROFILE"  "${CRYSTALITH_PROFILE:-}"
  _set_env_var "OPENAI_BASE_URL"     "OPENAI_BASE_URL_DOCKER" "${OPENAI_BASE_URL:-}"
  _set_env_var "CRYSTALITH_DEFAULT_EMBEDDING_MODEL" "CRYSTALITH_DEFAULT_EMBEDDING_MODEL_DOCKER" "${CRYSTALITH_DEFAULT_EMBEDDING_MODEL:-}"
  _set_env_var "BRIDGE_FORWARDS"     "BRIDGE_FORWARDS"     "${BRIDGE_FORWARDS:-}"
}

_set_env_var() {
  local source_name="$1"
  local target_key="$2"
  local value="$3"

  [[ -z "$value" ]] && return 0

  if grep -q "^${target_key}=" "$ENV_FILE" 2>/dev/null; then
    local existing
    existing="$(grep "^${target_key}=" "$ENV_FILE" | head -1 | cut -d= -f2-)"
    if [[ -n "$existing" ]]; then
      return 0
    fi
    # Replace empty value with env var value
    sed -i "s|^${target_key}=.*|${target_key}=${value}|" "$ENV_FILE"
    ok "  $ENV_FILE: ${target_key} <- \$${source_name}"
  else
    echo "${target_key}=${value}" >> "$ENV_FILE"
    ok "  $ENV_FILE: ${target_key} <- \$${source_name} (appended)"
  fi
}

# ---------------------------------------------------------------------------
# config/secrets.yaml initialization
# ---------------------------------------------------------------------------

SECRETS_FILE="config/secrets.yaml"

init_secrets_file() {
  if [[ ! -f "$SECRETS_FILE" ]]; then
    mkdir -p config
    cat > "$SECRETS_FILE" <<'YAML'
# Crystalith secrets — auto-generated by `just upsert-env-configs`.
# This file is gitignored. Do NOT commit.
# Re-run `just init` to update from environment variables.
YAML
    info "Created $SECRETS_FILE"
  else
    info "$SECRETS_FILE already exists, updating..."
  fi

  _set_secret "OPENAI_API_KEY"      "${OPENAI_API_KEY:-}"
  _set_secret "POSTGRES_PASSWORD"   "${POSTGRES_PASSWORD:-}"
  _set_secret "CRYSTALITH_API_KEY"  "${CRYSTALITH_API_KEY:-}"
  _set_secret "JINA_API_KEY"        "${JINA_API_KEY:-}"
  _set_secret "FIRECRAWL_API_KEY"   "${FIRECRAWL_API_KEY:-}"
  _set_secret "BROWSERLESS_TOKEN"   "${BROWSERLESS_TOKEN:-}"
}

_set_secret() {
  local key="$1"
  local value="$2"

  [[ -z "$value" ]] && return 0

  if grep -q "^${key}:" "$SECRETS_FILE" 2>/dev/null; then
    local existing
    existing="$(grep "^${key}:" "$SECRETS_FILE" | head -1 | sed 's/^[^:]*: *//' | tr -d '"' | tr -d "'")"
    if [[ -n "$existing" ]]; then
      return 0
    fi
    sed -i "s|^${key}:.*|${key}: \"${value}\"|" "$SECRETS_FILE"
    ok "  $SECRETS_FILE: ${key} <- \$${key}"
  else
    echo "${key}: \"${value}\"" >> "$SECRETS_FILE"
    ok "  $SECRETS_FILE: ${key} <- \$${key} (appended)"
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

info "Initializing local config from environment variables..."
echo ""

init_env_file
echo ""
init_secrets_file

echo ""
info "Summary:"
echo "  .env              — compose/build parameters"
echo "  config/secrets.yaml — runtime secrets"
echo ""

# Show what was detected
detected=0
for var in CRYSTALITH_PROFILE OPENAI_BASE_URL OPENAI_API_KEY CRYSTALITH_DEFAULT_EMBEDDING_MODEL \
           POSTGRES_PASSWORD CRYSTALITH_API_KEY JINA_API_KEY FIRECRAWL_API_KEY BROWSERLESS_TOKEN \
           BRIDGE_FORWARDS; do
  if [[ -n "${!var:-}" ]]; then
    ok "  \$$var detected"
    detected=$((detected + 1))
  fi
done

if [[ "$detected" -eq 0 ]]; then
  warn "  No env vars detected. Set them in your shell profile (~/.bashrc, ~/.zshrc, etc.)"
  warn "  and re-run 'just upsert-env-configs', or edit the files manually."
fi

echo ""
ok "Done. Run 'just up' to start."
