default:
    @just -l

dev:
    uv run python main.py

packages-test:
    #!/bin/bash
    for package in packages/*; do
        uv run --project $package pytest $package/tests
    done

test: packages-test
    uv run pytest

db-init:
    uv run scripts/db_init.py

vector-migrate:
    uv run scripts/vector_migrate.py
