# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.qa_response import QaResponse
from .raw_client import AsyncRawQaClient, RawQaClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class QaClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawQaClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawQaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawQaClient
        """
        return self._raw_client

    def ask_question(
        self,
        notebook_id: int,
        *,
        question: str,
        min_score: typing.Optional[float] = OMIT,
        session_id: typing.Optional[int] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QaResponse:
        """
        Parameters
        ----------
        notebook_id : int

        question : str

        min_score : typing.Optional[float]

        session_id : typing.Optional[int]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QaResponse
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.qa.ask_question(
            notebook_id=1,
            question="question",
        )
        """
        _response = self._raw_client.ask_question(
            notebook_id,
            question=question,
            min_score=min_score,
            session_id=session_id,
            source_ids=source_ids,
            top_k=top_k,
            request_options=request_options,
        )
        return _response.data

    def ask_question_stream(
        self,
        notebook_id: int,
        *,
        question: str,
        min_score: typing.Optional[float] = OMIT,
        session_id: typing.Optional[int] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Stream QA response using Server-Sent Events.

        Events:
        - `chunk`: Text chunk `{"text": "..."}`
        - `done`: Completion `{"citations": [...], "evidence": bool, "confidence": float, ...}`
        - `error`: Error `{"message": "..."}`

        Parameters
        ----------
        notebook_id : int

        question : str

        min_score : typing.Optional[float]

        session_id : typing.Optional[int]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            SSE stream of QA response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.qa.ask_question_stream(
            notebook_id=1,
            question="question",
        )
        """
        _response = self._raw_client.ask_question_stream(
            notebook_id,
            question=question,
            min_score=min_score,
            session_id=session_id,
            source_ids=source_ids,
            top_k=top_k,
            request_options=request_options,
        )
        return _response.data


class AsyncQaClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawQaClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawQaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawQaClient
        """
        return self._raw_client

    async def ask_question(
        self,
        notebook_id: int,
        *,
        question: str,
        min_score: typing.Optional[float] = OMIT,
        session_id: typing.Optional[int] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QaResponse:
        """
        Parameters
        ----------
        notebook_id : int

        question : str

        min_score : typing.Optional[float]

        session_id : typing.Optional[int]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QaResponse
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.qa.ask_question(
                notebook_id=1,
                question="question",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.ask_question(
            notebook_id,
            question=question,
            min_score=min_score,
            session_id=session_id,
            source_ids=source_ids,
            top_k=top_k,
            request_options=request_options,
        )
        return _response.data

    async def ask_question_stream(
        self,
        notebook_id: int,
        *,
        question: str,
        min_score: typing.Optional[float] = OMIT,
        session_id: typing.Optional[int] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Stream QA response using Server-Sent Events.

        Events:
        - `chunk`: Text chunk `{"text": "..."}`
        - `done`: Completion `{"citations": [...], "evidence": bool, "confidence": float, ...}`
        - `error`: Error `{"message": "..."}`

        Parameters
        ----------
        notebook_id : int

        question : str

        min_score : typing.Optional[float]

        session_id : typing.Optional[int]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            SSE stream of QA response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.qa.ask_question_stream(
                notebook_id=1,
                question="question",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.ask_question_stream(
            notebook_id,
            question=question,
            min_score=min_score,
            session_id=session_id,
            source_ids=source_ids,
            top_k=top_k,
            request_options=request_options,
        )
        return _response.data
