# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from ..types.qa_response import QaResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawQaClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def ask_question(
        self,
        notebook_id: int,
        *,
        question: str,
        min_score: typing.Optional[float] = OMIT,
        session_id: typing.Optional[int] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[QaResponse]:
        """
        Parameters
        ----------
        notebook_id : int

        question : str

        min_score : typing.Optional[float]

        session_id : typing.Optional[int]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[QaResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/qa",
            method="POST",
            json={
                "min_score": min_score,
                "question": question,
                "session_id": session_id,
                "source_ids": source_ids,
                "top_k": top_k,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    QaResponse,
                    parse_obj_as(
                        type_=QaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def ask_question_stream(
        self,
        notebook_id: int,
        *,
        question: str,
        min_score: typing.Optional[float] = OMIT,
        session_id: typing.Optional[int] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Any]:
        """
        Stream QA response using Server-Sent Events.

        Events:
        - `chunk`: Text chunk `{"text": "..."}`
        - `done`: Completion `{"citations": [...], "evidence": bool, "confidence": float, ...}`
        - `error`: Error `{"message": "..."}`

        Parameters
        ----------
        notebook_id : int

        question : str

        min_score : typing.Optional[float]

        session_id : typing.Optional[int]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            SSE stream of QA response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/qa/stream",
            method="POST",
            json={
                "min_score": min_score,
                "question": question,
                "session_id": session_id,
                "source_ids": source_ids,
                "top_k": top_k,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawQaClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def ask_question(
        self,
        notebook_id: int,
        *,
        question: str,
        min_score: typing.Optional[float] = OMIT,
        session_id: typing.Optional[int] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[QaResponse]:
        """
        Parameters
        ----------
        notebook_id : int

        question : str

        min_score : typing.Optional[float]

        session_id : typing.Optional[int]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[QaResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/qa",
            method="POST",
            json={
                "min_score": min_score,
                "question": question,
                "session_id": session_id,
                "source_ids": source_ids,
                "top_k": top_k,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    QaResponse,
                    parse_obj_as(
                        type_=QaResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def ask_question_stream(
        self,
        notebook_id: int,
        *,
        question: str,
        min_score: typing.Optional[float] = OMIT,
        session_id: typing.Optional[int] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Stream QA response using Server-Sent Events.

        Events:
        - `chunk`: Text chunk `{"text": "..."}`
        - `done`: Completion `{"citations": [...], "evidence": bool, "confidence": float, ...}`
        - `error`: Error `{"message": "..."}`

        Parameters
        ----------
        notebook_id : int

        question : str

        min_score : typing.Optional[float]

        session_id : typing.Optional[int]

        source_ids : typing.Optional[typing.Sequence[int]]

        top_k : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            SSE stream of QA response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/qa/stream",
            method="POST",
            json={
                "min_score": min_score,
                "question": question,
                "session_id": session_id,
                "source_ids": source_ids,
                "top_k": top_k,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
