# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.slide_draft_read import SlideDraftRead
from ..types.slide_generation_config import SlideGenerationConfig
from ..types.slide_outline import SlideOutline
from .raw_client import AsyncRawSlidesClient, RawSlidesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SlidesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSlidesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSlidesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSlidesClient
        """
        return self._raw_client

    def get_latest_draft(
        self, notebook_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.slides.get_latest_draft(
            notebook_id=1,
        )
        """
        _response = self._raw_client.get_latest_draft(notebook_id, request_options=request_options)
        return _response.data

    def create_draft(
        self,
        notebook_id: int,
        *,
        title: typing.Optional[str] = OMIT,
        prompt: typing.Optional[str] = OMIT,
        engine: typing.Optional[str] = OMIT,
        chunk_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        generation_config: typing.Optional[SlideGenerationConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        title : typing.Optional[str]

        prompt : typing.Optional[str]

        engine : typing.Optional[str]
            Rendering engine (default: slidev)

        chunk_ids : typing.Optional[typing.Sequence[int]]

        source_ids : typing.Optional[typing.Sequence[int]]

        generation_config : typing.Optional[SlideGenerationConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.slides.create_draft(
            notebook_id=1,
        )
        """
        _response = self._raw_client.create_draft(
            notebook_id,
            title=title,
            prompt=prompt,
            engine=engine,
            chunk_ids=chunk_ids,
            source_ids=source_ids,
            generation_config=generation_config,
            request_options=request_options,
        )
        return _response.data

    def get_draft(
        self, notebook_id: int, slide_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.slides.get_draft(
            notebook_id=1,
            slide_id=1,
        )
        """
        _response = self._raw_client.get_draft(notebook_id, slide_id, request_options=request_options)
        return _response.data

    def update_draft(
        self,
        notebook_id: int,
        slide_id: int,
        *,
        title: typing.Optional[str] = OMIT,
        prompt: typing.Optional[str] = OMIT,
        engine: typing.Optional[str] = OMIT,
        chunk_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        generation_config: typing.Optional[SlideGenerationConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        title : typing.Optional[str]

        prompt : typing.Optional[str]

        engine : typing.Optional[str]

        chunk_ids : typing.Optional[typing.Sequence[int]]

        source_ids : typing.Optional[typing.Sequence[int]]

        generation_config : typing.Optional[SlideGenerationConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.slides.update_draft(
            notebook_id=1,
            slide_id=1,
        )
        """
        _response = self._raw_client.update_draft(
            notebook_id,
            slide_id,
            title=title,
            prompt=prompt,
            engine=engine,
            chunk_ids=chunk_ids,
            source_ids=source_ids,
            generation_config=generation_config,
            request_options=request_options,
        )
        return _response.data

    def update_outline(
        self,
        notebook_id: int,
        slide_id: int,
        *,
        outline: SlideOutline,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        outline : SlideOutline

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient, SlideOutline, SlideOutlineItem

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.slides.update_outline(
            notebook_id=1,
            slide_id=1,
            outline=SlideOutline(
                title="title",
                slides=[
                    SlideOutlineItem(
                        title="title",
                    )
                ],
            ),
        )
        """
        _response = self._raw_client.update_outline(
            notebook_id, slide_id, outline=outline, request_options=request_options
        )
        return _response.data

    def update_markdown(
        self, notebook_id: int, slide_id: int, *, markdown: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        markdown : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.slides.update_markdown(
            notebook_id=1,
            slide_id=1,
            markdown="markdown",
        )
        """
        _response = self._raw_client.update_markdown(
            notebook_id, slide_id, markdown=markdown, request_options=request_options
        )
        return _response.data

    def generate_outline_stream(
        self,
        notebook_id: int,
        slide_id: int,
        *,
        model_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        model_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.slides.generate_outline_stream(
            notebook_id=1,
            slide_id=1,
        )
        """
        _response = self._raw_client.generate_outline_stream(
            notebook_id, slide_id, model_id=model_id, request_options=request_options
        )
        return _response.data

    def generate_markdown_stream(
        self,
        notebook_id: int,
        slide_id: int,
        *,
        model_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        model_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.slides.generate_markdown_stream(
            notebook_id=1,
            slide_id=1,
        )
        """
        _response = self._raw_client.generate_markdown_stream(
            notebook_id, slide_id, model_id=model_id, request_options=request_options
        )
        return _response.data


class AsyncSlidesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSlidesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSlidesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSlidesClient
        """
        return self._raw_client

    async def get_latest_draft(
        self, notebook_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.slides.get_latest_draft(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_latest_draft(notebook_id, request_options=request_options)
        return _response.data

    async def create_draft(
        self,
        notebook_id: int,
        *,
        title: typing.Optional[str] = OMIT,
        prompt: typing.Optional[str] = OMIT,
        engine: typing.Optional[str] = OMIT,
        chunk_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        generation_config: typing.Optional[SlideGenerationConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        title : typing.Optional[str]

        prompt : typing.Optional[str]

        engine : typing.Optional[str]
            Rendering engine (default: slidev)

        chunk_ids : typing.Optional[typing.Sequence[int]]

        source_ids : typing.Optional[typing.Sequence[int]]

        generation_config : typing.Optional[SlideGenerationConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.slides.create_draft(
                notebook_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_draft(
            notebook_id,
            title=title,
            prompt=prompt,
            engine=engine,
            chunk_ids=chunk_ids,
            source_ids=source_ids,
            generation_config=generation_config,
            request_options=request_options,
        )
        return _response.data

    async def get_draft(
        self, notebook_id: int, slide_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.slides.get_draft(
                notebook_id=1,
                slide_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_draft(notebook_id, slide_id, request_options=request_options)
        return _response.data

    async def update_draft(
        self,
        notebook_id: int,
        slide_id: int,
        *,
        title: typing.Optional[str] = OMIT,
        prompt: typing.Optional[str] = OMIT,
        engine: typing.Optional[str] = OMIT,
        chunk_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        source_ids: typing.Optional[typing.Sequence[int]] = OMIT,
        generation_config: typing.Optional[SlideGenerationConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        title : typing.Optional[str]

        prompt : typing.Optional[str]

        engine : typing.Optional[str]

        chunk_ids : typing.Optional[typing.Sequence[int]]

        source_ids : typing.Optional[typing.Sequence[int]]

        generation_config : typing.Optional[SlideGenerationConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.slides.update_draft(
                notebook_id=1,
                slide_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_draft(
            notebook_id,
            slide_id,
            title=title,
            prompt=prompt,
            engine=engine,
            chunk_ids=chunk_ids,
            source_ids=source_ids,
            generation_config=generation_config,
            request_options=request_options,
        )
        return _response.data

    async def update_outline(
        self,
        notebook_id: int,
        slide_id: int,
        *,
        outline: SlideOutline,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        outline : SlideOutline

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient, SlideOutline, SlideOutlineItem

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.slides.update_outline(
                notebook_id=1,
                slide_id=1,
                outline=SlideOutline(
                    title="title",
                    slides=[
                        SlideOutlineItem(
                            title="title",
                        )
                    ],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_outline(
            notebook_id, slide_id, outline=outline, request_options=request_options
        )
        return _response.data

    async def update_markdown(
        self, notebook_id: int, slide_id: int, *, markdown: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SlideDraftRead:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        markdown : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SlideDraftRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.slides.update_markdown(
                notebook_id=1,
                slide_id=1,
                markdown="markdown",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_markdown(
            notebook_id, slide_id, markdown=markdown, request_options=request_options
        )
        return _response.data

    async def generate_outline_stream(
        self,
        notebook_id: int,
        slide_id: int,
        *,
        model_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        model_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.slides.generate_outline_stream(
                notebook_id=1,
                slide_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.generate_outline_stream(
            notebook_id, slide_id, model_id=model_id, request_options=request_options
        )
        return _response.data

    async def generate_markdown_stream(
        self,
        notebook_id: int,
        slide_id: int,
        *,
        model_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Parameters
        ----------
        notebook_id : int

        slide_id : int

        model_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.slides.generate_markdown_stream(
                notebook_id=1,
                slide_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.generate_markdown_stream(
            notebook_id, slide_id, model_id=model_id, request_options=request_options
        )
        return _response.data
