# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.citation import Citation
from ..types.http_validation_error import HttpValidationError
from ..types.message_read import MessageRead
from .types.message_create_role import MessageCreateRole

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawMessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_messages(
        self,
        notebook_id: int,
        session_id: int,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.List[MessageRead]]:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[MessageRead]]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/sessions/{jsonable_encoder(session_id)}/messages",
            method="GET",
            params={
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[MessageRead],
                    parse_obj_as(
                        type_=typing.List[MessageRead],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_message(
        self,
        notebook_id: int,
        session_id: int,
        *,
        content: str,
        role: MessageCreateRole,
        citations: typing.Optional[typing.Sequence[Citation]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[MessageRead]:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        content : str

        role : MessageCreateRole

        citations : typing.Optional[typing.Sequence[Citation]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageRead]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/sessions/{jsonable_encoder(session_id)}/messages",
            method="POST",
            json={
                "citations": convert_and_respect_annotation_metadata(
                    object_=citations, annotation=typing.Optional[typing.Sequence[Citation]], direction="write"
                ),
                "content": content,
                "role": role,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageRead,
                    parse_obj_as(
                        type_=MessageRead,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_messages(
        self,
        notebook_id: int,
        session_id: int,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.List[MessageRead]]:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[MessageRead]]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/sessions/{jsonable_encoder(session_id)}/messages",
            method="GET",
            params={
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[MessageRead],
                    parse_obj_as(
                        type_=typing.List[MessageRead],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_message(
        self,
        notebook_id: int,
        session_id: int,
        *,
        content: str,
        role: MessageCreateRole,
        citations: typing.Optional[typing.Sequence[Citation]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[MessageRead]:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        content : str

        role : MessageCreateRole

        citations : typing.Optional[typing.Sequence[Citation]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageRead]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/notebooks/{jsonable_encoder(notebook_id)}/sessions/{jsonable_encoder(session_id)}/messages",
            method="POST",
            json={
                "citations": convert_and_respect_annotation_metadata(
                    object_=citations, annotation=typing.Optional[typing.Sequence[Citation]], direction="write"
                ),
                "content": content,
                "role": role,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageRead,
                    parse_obj_as(
                        type_=MessageRead,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
