# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.citation import Citation
from ..types.message_read import MessageRead
from .raw_client import AsyncRawMessagesClient, RawMessagesClient
from .types.message_create_role import MessageCreateRole

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMessagesClient
        """
        return self._raw_client

    def list_messages(
        self,
        notebook_id: int,
        session_id: int,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[MessageRead]:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[MessageRead]
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.messages.list_messages(
            notebook_id=1,
            session_id=1,
        )
        """
        _response = self._raw_client.list_messages(
            notebook_id, session_id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def create_message(
        self,
        notebook_id: int,
        session_id: int,
        *,
        content: str,
        role: MessageCreateRole,
        citations: typing.Optional[typing.Sequence[Citation]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageRead:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        content : str

        role : MessageCreateRole

        citations : typing.Optional[typing.Sequence[Citation]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageRead
            Successful Response

        Examples
        --------
        from crystalith import CrystalithClient

        client = CrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )
        client.messages.create_message(
            notebook_id=1,
            session_id=1,
            content="content",
            role="assistant",
        )
        """
        _response = self._raw_client.create_message(
            notebook_id, session_id, content=content, role=role, citations=citations, request_options=request_options
        )
        return _response.data


class AsyncMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMessagesClient
        """
        return self._raw_client

    async def list_messages(
        self,
        notebook_id: int,
        session_id: int,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[MessageRead]:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[MessageRead]
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.messages.list_messages(
                notebook_id=1,
                session_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_messages(
            notebook_id, session_id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def create_message(
        self,
        notebook_id: int,
        session_id: int,
        *,
        content: str,
        role: MessageCreateRole,
        citations: typing.Optional[typing.Sequence[Citation]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageRead:
        """
        Parameters
        ----------
        notebook_id : int

        session_id : int

        content : str

        role : MessageCreateRole

        citations : typing.Optional[typing.Sequence[Citation]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageRead
            Successful Response

        Examples
        --------
        import asyncio

        from crystalith import AsyncCrystalithClient

        client = AsyncCrystalithClient(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.messages.create_message(
                notebook_id=1,
                session_id=1,
                content="content",
                role="assistant",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_message(
            notebook_id, session_id, content=content, role=role, citations=citations, request_options=request_options
        )
        return _response.data
