# This file was auto-generated by Fern from our API Definition.

import typing

ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus = typing.Union[
    typing.Literal["planning", "searching", "analyzing", "waiting_user", "completed", "cancelled"], typing.Any
]
