# This file was auto-generated by Fern from our API Definition.

import typing

ListResearchSessionsV1NotebooksNotebookIdResearchGetRequestStatus = typing.Union[
    typing.Literal["analyzing", "cancelled", "completed", "planning", "searching", "waiting_user"], typing.Any
]
